{{- $protocol := ternary  "https" "http" .Values.adminUI.tls.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-admin-api
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
data:
  KRE_API_LOG_LEVEL: {{ .Values.adminApi.logLevel }}
  KRE_DEVELOPMENT_MODE: "{{ .Values.developmentMode }}"
  KRE_RELEASE_NAME: "{{ .Release.Name }}"
  KRE_ADMIN_FRONTEND_BASE_URL: "{{ .Values.config.admin.frontendBaseURL }}"
  KRE_ADMIN_API_BASE_URL: "{{ $protocol }}://{{ .Values.config.admin.apiHost }}"
  KRE_ADMIN_CORS_ENABLED: "{{ .Values.config.admin.corsEnabled }}"
  KRE_SERVICES_K8S_MANAGER: "{{ .Release.Name }}-k8s-manager:50051"
  KRE_MONGODB_MONGOEXPRESS_ADDRESS: {{ include "mongoExpress.name" . }}
  KRE_BASE_DOMAIN_NAME: {{ .Values.config.baseDomainName }}
  KRE_ADMIN_STORAGE_PATH: {{ .Values.adminApi.storage.path }}
  KRE_ADMIN_API_ADDRESS: ":8080"
  # SMTP
  KRE_SMTP_ENABLED: "{{ .Values.config.smtp.enabled }}"
  {{- if .Values.config.smtp.enabled }}
  KRE_SMTP_SENDER: "{{ .Values.config.smtp.sender }}"
  KRE_SMTP_SENDER_NAME: "{{ .Values.config.smtp.senderName }}"
  KRE_SMTP_HOST: "{{ .Values.config.smtp.host }}"
  KRE_SMTP_PORT: "{{ .Values.config.smtp.port }}"
  {{- end }}
  # Auth
  KRE_AUTH_VERIFICATION_CODE_DURATION_IN_MINUTES: "{{ .Values.config.auth.verificationCodeDurationInMinutes }}"
  KRE_AUTH_SECURE_COOKIE: "{{ .Values.config.auth.secureCookie }}"
  KRE_AUTH_COOKIE_DOMAIN: "{{ .Values.config.auth.cookieDomain }}"
  #InfluxDB
  KRE_INFLUXDB_ADDRESS: {{ include "kre-influxdb.influxURL" . }}
