{{ if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
  {{ else if .Capabilities.APIVersions.Has "extensions/v1beta1" }}
apiVersion: extensions/v1beta1
  {{ end }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin-api
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "admin-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "admin-api.labels" . | nindent 8 }}
        type: admin
      annotations:
        helm.sh/restart-deployment: {{ randAlphaNum 5 | quote }}
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
        - name: create-admin-api-files-directory
          image: alpine:3.10
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - -c
          - mkdir -p {{ .Values.adminApi.storage.path }} && chown 10001:10001 {{ .Values.adminApi.storage.path }}
          volumeMounts:
            - name: admin-api-pv-storage
              mountPath: {{ .Values.adminApi.storage.path }}
      containers:
        - name: {{ .Release.Name }}-admin-api
          image: {{ .Values.adminApi.image.repository }}:{{ .Values.adminApi.image.tag }}
          imagePullPolicy: {{ .Values.adminApi.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secrets
          env:
            - name: KRE_ADMIN_STORAGE_PATH
              value: {{ .Values.adminApi.storage.path }}
            - name: KRE_ADMIN_API_ADDRESS
              value: ":8080"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KRE_API_LOG_LEVEL
              value: {{ .Values.adminApi.logLevel }}
          ports:
            - containerPort: 8080
              protocol: TCP
              name: grpc
          volumeMounts:
            - name: admin-api-pv-storage
              mountPath: {{ .Values.adminApi.storage.path }}
      volumes:
        - name: admin-api-pv-storage
          persistentVolumeClaim:
            claimName: admin-api-pv-claim
