{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin-api-ingress
  annotations:
    {{- include "kre-admin-api.annotations" . | nindent 4 }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-api-ingress
spec:
  {{- if .Values.adminApi.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.adminApi.host }}
      secretName: {{ .Values.adminApi.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminApi.host }}
      http:
        paths:
          {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: admin-api
                port:
                  number: 80
          {{ else }}
          - path: /
            backend:
              serviceName: admin-api
              servicePort: grpc
          {{ end }} 
