apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin-api
  {{- with .Values.adminApi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
spec:
  {{- if .Values.adminApi.ingress.className }}
  ingressClassName: {{ .Values.adminApi.ingress.className }}
  {{- end }}
  {{- if .Values.adminApi.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.adminApi.host }}
      secretName: {{ .Values.adminApi.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminApi.host }}
      http:
        paths:
          - path: "/"
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ .Release.Name }}-admin-api
                port:
                  name: grpc
              {{- else }}
              serviceName: {{ .Release.Name }}-admin-api
              servicePort: grpc
              {{- end }}
