apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin-api-ingress
  {{- with .Values.adminApi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.adminApi.ingress.className }}
  {{- if .Values.adminApi.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.adminApi.host }}
      secretName: {{ .Values.adminApi.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminApi.host }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: admin-api
                port:
                  name: grpc
