{{- if and .Values.certManager.enabled .Values.adminApi.tls.enabled }}
{{ if .Capabilities.APIVersions.Has "cert-manager.io/v1alpha3" }}
apiVersion: cert-manager.io/v1alpha3
{{ else }}
apiVersion: cert-manager.io/v1
{{ end }}
kind: Issuer
metadata:
  name: {{ .Release.Name }}-admin-api
spec:
  acme:
    server: {{ .Values.certManager.acme.server }}
    email: {{ .Values.certManager.acme.email }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-admin-api
    solvers:
      {{- with .Values.certManager.dns01 }}
      - dns01:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.certManager.http01 }}
      - http01:
        {{- toYaml . | nindent 10 }}
      {{- end }}
{{- end }}
