apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-admin-api
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
data:
  KRE_AUTH_JWT_SIGN_SECRET: {{ .Values.config.auth.jwtSignSecret | b64enc }}
  {{- if .Values.config.smtp.enabled}}
  KRE_SMTP_USER: {{ .Values.config.smtp.user | b64enc }}
  KRE_SMTP_PASS: {{ .Values.config.smtp.pass | b64enc }}
  {{- end }}
  KRE_AUTH_API_TOKEN_SECRET: "{{ .Values.config.auth.apiTokenSecret | b64enc }}"
