apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-api
  labels:
    {{- include "admin-api.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: grpc
  selector:
    {{- include "admin-api.selectorLabels" . | nindent 4 }}
