apiVersion: v1
kind: Service
metadata:
  name: kre-nats
  labels:
    {{ include "runtime.labels" . | nindent 4 }}
    app: kre-nats
spec:
  selector:
    app: kre-nats
  ports:
    - name: nats
      protocol: TCP
      port: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
