// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import versionpb "gitlab.com/konstellation/konstellation-ce/kre/k8s-manager/proto/versionpb"

// VersionServiceClient is an autogenerated mock type for the VersionServiceClient type
type VersionServiceClient struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, in, opts
func (_m *VersionServiceClient) Publish(ctx context.Context, in *versionpb.Request, opts ...grpc.CallOption) (*versionpb.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *versionpb.Response
	if rf, ok := ret.Get(0).(func(context.Context, *versionpb.Request, ...grpc.CallOption) *versionpb.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*versionpb.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *versionpb.Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Start provides a mock function with given fields: ctx, in, opts
func (_m *VersionServiceClient) Start(ctx context.Context, in *versionpb.Request, opts ...grpc.CallOption) (*versionpb.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *versionpb.Response
	if rf, ok := ret.Get(0).(func(context.Context, *versionpb.Request, ...grpc.CallOption) *versionpb.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*versionpb.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *versionpb.Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Stop provides a mock function with given fields: ctx, in, opts
func (_m *VersionServiceClient) Stop(ctx context.Context, in *versionpb.Request, opts ...grpc.CallOption) (*versionpb.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *versionpb.Response
	if rf, ok := ret.Get(0).(func(context.Context, *versionpb.Request, ...grpc.CallOption) *versionpb.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*versionpb.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *versionpb.Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unpublish provides a mock function with given fields: ctx, in, opts
func (_m *VersionServiceClient) Unpublish(ctx context.Context, in *versionpb.Request, opts ...grpc.CallOption) (*versionpb.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *versionpb.Response
	if rf, ok := ret.Get(0).(func(context.Context, *versionpb.Request, ...grpc.CallOption) *versionpb.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*versionpb.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *versionpb.Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConfig provides a mock function with given fields: ctx, in, opts
func (_m *VersionServiceClient) UpdateConfig(ctx context.Context, in *versionpb.Request, opts ...grpc.CallOption) (*versionpb.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *versionpb.Response
	if rf, ok := ret.Get(0).(func(context.Context, *versionpb.Request, ...grpc.CallOption) *versionpb.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*versionpb.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *versionpb.Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
