apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  KRE_MONGODB_ADDRESS: {{ include "runtime.mongoURI" . | b64enc }}
  KRE_AUTH_JWT_SIGN_SECRET: {{ .Values.config.auth.jwtSignSecret | b64enc }}
  {{- if .Values.config.smtp.enabled}}
  KRE_SMTP_USER: {{ .Values.config.smtp.user | b64enc }}
  KRE_SMTP_PASS: {{ .Values.config.smtp.pass | b64enc }}
  {{- end }}
  ## ApiToken
  KRE_AUTH_API_TOKEN_SECRET: "{{ .Values.config.auth.apiTokenSecret | b64enc }}"

  # Monoruntime config
  MONORUNTIME_MINIO_SECRET_KEY: {{ .Values.minio.credentials.secretKey | b64enc }}
  MONORUNTIME_MONGO_USERNAME: {{ .Values.mongodb.mongodbUsername | b64enc }}
  MONORUNTIME_MONGO_PASSWORD: {{ .Values.mongodb.mongodbPassword | b64enc }}

  # Runtime config
  KRE_RUNTIME_MONGO_URI: {{ include "runtime.mongoURI" . | b64enc }}
