{{ if .Values.rbac.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: kre-admin
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - services
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - "*"
{{ end }}
