# Automatically generated by HonestCode
# Do not edit this file as it will be overwritten

Feature: Settings
  As an API Client
  I want to manage the KRE settings

  Scenario: General settings management successfully
    Given the API client has already logged in
    And the Session lifetime in days time is 35
    When the API client sets the Session lifetime in days time to 45
    Then the API client will receive the general settings with the Session lifetime in days time as 45
