// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import minio "gitlab.com/konstellation/konstellation-ce/kre/admin-api/adapter/repository/minio"
import mock "github.com/stretchr/testify/mock"

// Bucket is an autogenerated mock type for the Bucket type
type Bucket struct {
	mock.Mock
}

// CopyDir provides a mock function with given fields: dir, minioClient
func (_m *Bucket) CopyDir(dir string, minioClient *minio.MinioClient) error {
	ret := _m.Called(dir, minioClient)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *minio.MinioClient) error); ok {
		r0 = rf(dir, minioClient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
