// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LoginLinkTransport is an autogenerated mock type for the LoginLinkTransport type
type LoginLinkTransport struct {
	mock.Mock
}

// Send provides a mock function with given fields: recipient, verificationCode
func (_m *LoginLinkTransport) Send(recipient string, verificationCode string) error {
	ret := _m.Called(recipient, verificationCode)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(recipient, verificationCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
