// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entity "gitlab.com/konstellation/kre/admin-api/domain/entity"
import gql "gitlab.com/konstellation/kre/admin-api/adapter/gql"
import mock "github.com/stretchr/testify/mock"

// NodeResolver is an autogenerated mock type for the NodeResolver type
type NodeResolver struct {
	mock.Mock
}

// Status provides a mock function with given fields: ctx, obj
func (_m *NodeResolver) Status(ctx context.Context, obj *entity.Node) (gql.NodeStatus, error) {
	ret := _m.Called(ctx, obj)

	var r0 gql.NodeStatus
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Node) gql.NodeStatus); ok {
		r0 = rf(ctx, obj)
	} else {
		r0 = ret.Get(0).(gql.NodeStatus)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.Node) error); ok {
		r1 = rf(ctx, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
