// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gql "gitlab.com/konstellation/konstellation-ce/kre/admin-api/adapter/gql"
import mock "github.com/stretchr/testify/mock"

// ResolverRoot is an autogenerated mock type for the ResolverRoot type
type ResolverRoot struct {
	mock.Mock
}

// Mutation provides a mock function with given fields:
func (_m *ResolverRoot) Mutation() gql.MutationResolver {
	ret := _m.Called()

	var r0 gql.MutationResolver
	if rf, ok := ret.Get(0).(func() gql.MutationResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gql.MutationResolver)
		}
	}

	return r0
}

// Query provides a mock function with given fields:
func (_m *ResolverRoot) Query() gql.QueryResolver {
	ret := _m.Called()

	var r0 gql.QueryResolver
	if rf, ok := ret.Get(0).(func() gql.QueryResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gql.QueryResolver)
		}
	}

	return r0
}

// Subscription provides a mock function with given fields:
func (_m *ResolverRoot) Subscription() gql.SubscriptionResolver {
	ret := _m.Called()

	var r0 gql.SubscriptionResolver
	if rf, ok := ret.Get(0).(func() gql.SubscriptionResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gql.SubscriptionResolver)
		}
	}

	return r0
}
