// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import grpc "google.golang.org/grpc"
import k8smanagerpb "gitlab.com/konstellation/konstellation-ce/kre/admin-api/k8smanagerpb"
import mock "github.com/stretchr/testify/mock"

// RuntimeServiceClient is an autogenerated mock type for the RuntimeServiceClient type
type RuntimeServiceClient struct {
	mock.Mock
}

// CheckRuntimeIsCreated provides a mock function with given fields: ctx, in, opts
func (_m *RuntimeServiceClient) CheckRuntimeIsCreated(ctx context.Context, in *k8smanagerpb.CheckRuntimeIsCreatedRequest, opts ...grpc.CallOption) (*k8smanagerpb.CheckRuntimeIsCreatedResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *k8smanagerpb.CheckRuntimeIsCreatedResponse
	if rf, ok := ret.Get(0).(func(context.Context, *k8smanagerpb.CheckRuntimeIsCreatedRequest, ...grpc.CallOption) *k8smanagerpb.CheckRuntimeIsCreatedResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*k8smanagerpb.CheckRuntimeIsCreatedResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *k8smanagerpb.CheckRuntimeIsCreatedRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRuntime provides a mock function with given fields: ctx, in, opts
func (_m *RuntimeServiceClient) CreateRuntime(ctx context.Context, in *k8smanagerpb.CreateRuntimeRequest, opts ...grpc.CallOption) (*k8smanagerpb.CreateRuntimeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *k8smanagerpb.CreateRuntimeResponse
	if rf, ok := ret.Get(0).(func(context.Context, *k8smanagerpb.CreateRuntimeRequest, ...grpc.CallOption) *k8smanagerpb.CreateRuntimeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*k8smanagerpb.CreateRuntimeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *k8smanagerpb.CreateRuntimeRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
