{{- $protocol := ternary  "https" "http" .Values.adminUI.tls.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-admin-ui
  labels:
    {{- include "admin-ui.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "API_BASE_URL": "{{ $protocol }}://{{ .Values.config.admin.apiHost }}"
    }
