apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin-ui
  labels:
    {{- include "admin-ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "admin-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "admin-ui.labels" . | nindent 8 }}
        type: admin
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/engine/admin-ui/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.adminUI.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminUI.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminUI.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-admin-ui
          image: {{ .Values.adminUI.image.repository }}:{{ .Values.adminUI.image.tag }}
          imagePullPolicy: {{ .Values.adminUI.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config/config.json
              subPath: config.json
          ports:
            - containerPort: 8080
              protocol: TCP
              name: web
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-admin-ui
