apiVersion: v1
kind: Service
metadata:
  name: admin-api
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-api
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: grpc
  selector:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-api
