{{- if and ( eq .Values.engine.certManager.enabled true) ( eq .Values.engine.config.runtime.entrypoint.tls true) }}
apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: clusterissuer-runtimes-entrypoints
spec:
  acme:
    server: {{ .Values.engine.certManager.acme.server }}
    email: {{ .Values.engine.certManager.acme.email }}
    privateKeySecretRef:
      name: clusterissuer-runtimes
    solvers:
            {{ if hasKey .Values.engine.certManager "dns01" -}}
      - dns01:
          route53:
            region: {{ .Values.engine.certManager.dns01.route53.region }}
            accessKeyID: {{ .Values.engine.certManager.dns01.route53.accessKeyID }}
            hostedZoneID: {{ .Values.engine.certManager.dns01.route53.hostedZoneID }}
            secretAccessKeySecretRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
            {{ else -}}
      - http01:
          ingress:
            class: nginx
        {{ end -}}
        {{- end }}
