{{- $protocol := ternary  "https" "http" .Values.engine.adminUI.tls.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ template "kre.fullname" . }}-admin-api
data:
  KRE_DEVELOPMENT_MODE: "{{ .Values.developmentMode }}"
  # Runtime Entrypoint TLS
  KRE_ENTRYPOINT_TLS: "{{ .Values.engine.config.runtime.entrypoint.tls }}"
  # Admin
  KRE_ADMIN_FRONTEND_BASE_URL: "{{ .Values.engine.config.admin.frontendBaseURL }}"
  KRE_ADMIN_API_BASE_URL: "{{ $protocol }}://{{ .Values.engine.config.admin.apiHost }}"
  KRE_ADMIN_CORS_ENABLED: "{{ .Values.engine.config.admin.corsEnabled }}"
  KRE_SERVICES_K8S_MANAGER: "k8s-manager:50051"
  # K8S MANAGER
  KRE_BASE_DOMAIN_NAME: {{ .Values.engine.config.baseDomainName }}
  KRE_SHARED_STORAGECLASS: {{ .Values.engine.config.runtime.sharedStorageClass }}
  KRE_SHARED_STORAGE_SIZE: {{ .Values.engine.config.runtime.sharedStorageSize }}
  KRE_ENTRYPOINT_REQUEST_TIMEOUT: "30"

  # SMTP
  KRE_SMTP_ENABLED: "{{ .Values.engine.config.smtp.enabled }}"
  {{- if .Values.engine.config.smtp.enabled }}
  KRE_SMTP_SENDER: "{{ .Values.engine.config.smtp.sender }}"
  KRE_SMTP_SENDER_NAME: "{{ .Values.engine.config.smtp.senderName }}"
  KRE_SMTP_HOST: "{{ .Values.engine.config.smtp.host }}"
  KRE_SMTP_PORT: "{{ .Values.engine.config.smtp.port }}"
  {{- end }}
  # Auth
  KRE_AUTH_VERIFICATION_CODE_DURATION_IN_MINUTES: "{{ .Values.engine.config.auth.verificationCodeDurationInMinutes }}"
  KRE_AUTH_SECURE_COOKIE: "{{ .Values.engine.config.auth.secureCookie }}"
  KRE_AUTH_COOKIE_DOMAIN: "{{ .Values.engine.config.auth.cookieDomain }}"
  # Prometheus
  KRE_PROMETHEUS_URL: "http://prometheus-operated:9090"
  # NATS Streaming
  KRE_NATS_STORAGECLASS: "{{ .Values.engine.config.runtime.nats_streaming.storage.className }}"
  KRE_NATS_STORAGE_SIZE: "{{ .Values.engine.config.runtime.nats_streaming.storage.size }}"
  # MongoDB
  KRE_MONGODB_STORAGECLASS: "{{ .Values.engine.config.runtime.mongodb.persistentVolume.storageClass }}"
  KRE_MONGODB_STORAGE_SIZE: "{{ .Values.engine.config.runtime.mongodb.persistentVolume.size }}"
  # Chronograf
  KRE_CHRONOGRAF_STORAGECLASS: "{{ .Values.engine.config.runtime.chronograf.persistentVolume.storageClass }}"
  KRE_CHRONOGRAF_STORAGE_SIZE: "{{ .Values.engine.config.runtime.chronograf.persistentVolume.size }}"
  #InfluxDB
  KRE_INFLUXDB_STORAGECLASS: "{{ .Values.engine.config.runtime.influxdb.persistentVolume.storageClass }}"
  KRE_INFLUXDB_STORAGE_SIZE: "{{ .Values.engine.config.runtime.influxdb.persistentVolume.size }}"
