apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-engine-secrets
type: Opaque
data:
  KRE_MONGODB_ADDRESS: {{ printf "mongodb://%s:%s@kre-mongo:27017/%s" .Values.engine.mongodb.mongodbUsername .Values.engine.mongodb.mongodbPassword "kre" | b64enc }}
  KRE_AUTH_JWT_SIGN_SECRET: {{ .Values.engine.config.auth.jwtSignSecret | b64enc }}
        {{- if .Values.engine.config.smtp.enabled}}
  KRE_SMTP_USER: {{ .Values.engine.config.smtp.user | b64enc }}
  KRE_SMTP_PASS: {{ .Values.engine.config.smtp.pass | b64enc }}
        {{- end }}
  ## ApiToken
  KRE_AUTH_API_TOKEN_SECRET: "{{ .Values.engine.config.auth.apiTokenSecret | b64enc }}"
