// Code generated by protoc-gen-go. DO NOT EDIT.
// source: runtimepb/runtime.proto

package runtimepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Runtime struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Minio                *Runtime_MinioConf `protobuf:"bytes,2,opt,name=minio,proto3" json:"minio,omitempty"`
	Mongo                *Runtime_MongoConf `protobuf:"bytes,3,opt,name=mongo,proto3" json:"mongo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Runtime) Reset()         { *m = Runtime{} }
func (m *Runtime) String() string { return proto.CompactTextString(m) }
func (*Runtime) ProtoMessage()    {}
func (*Runtime) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{0}
}

func (m *Runtime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Runtime.Unmarshal(m, b)
}
func (m *Runtime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Runtime.Marshal(b, m, deterministic)
}
func (m *Runtime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Runtime.Merge(m, src)
}
func (m *Runtime) XXX_Size() int {
	return xxx_messageInfo_Runtime.Size(m)
}
func (m *Runtime) XXX_DiscardUnknown() {
	xxx_messageInfo_Runtime.DiscardUnknown(m)
}

var xxx_messageInfo_Runtime proto.InternalMessageInfo

func (m *Runtime) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Runtime) GetMinio() *Runtime_MinioConf {
	if m != nil {
		return m.Minio
	}
	return nil
}

func (m *Runtime) GetMongo() *Runtime_MongoConf {
	if m != nil {
		return m.Mongo
	}
	return nil
}

type Runtime_MongoConf struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Runtime_MongoConf) Reset()         { *m = Runtime_MongoConf{} }
func (m *Runtime_MongoConf) String() string { return proto.CompactTextString(m) }
func (*Runtime_MongoConf) ProtoMessage()    {}
func (*Runtime_MongoConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{0, 0}
}

func (m *Runtime_MongoConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Runtime_MongoConf.Unmarshal(m, b)
}
func (m *Runtime_MongoConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Runtime_MongoConf.Marshal(b, m, deterministic)
}
func (m *Runtime_MongoConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Runtime_MongoConf.Merge(m, src)
}
func (m *Runtime_MongoConf) XXX_Size() int {
	return xxx_messageInfo_Runtime_MongoConf.Size(m)
}
func (m *Runtime_MongoConf) XXX_DiscardUnknown() {
	xxx_messageInfo_Runtime_MongoConf.DiscardUnknown(m)
}

var xxx_messageInfo_Runtime_MongoConf proto.InternalMessageInfo

func (m *Runtime_MongoConf) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Runtime_MongoConf) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Runtime_MinioConf struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
	SecretKey            string   `protobuf:"bytes,2,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Runtime_MinioConf) Reset()         { *m = Runtime_MinioConf{} }
func (m *Runtime_MinioConf) String() string { return proto.CompactTextString(m) }
func (*Runtime_MinioConf) ProtoMessage()    {}
func (*Runtime_MinioConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{0, 1}
}

func (m *Runtime_MinioConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Runtime_MinioConf.Unmarshal(m, b)
}
func (m *Runtime_MinioConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Runtime_MinioConf.Marshal(b, m, deterministic)
}
func (m *Runtime_MinioConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Runtime_MinioConf.Merge(m, src)
}
func (m *Runtime_MinioConf) XXX_Size() int {
	return xxx_messageInfo_Runtime_MinioConf.Size(m)
}
func (m *Runtime_MinioConf) XXX_DiscardUnknown() {
	xxx_messageInfo_Runtime_MinioConf.DiscardUnknown(m)
}

var xxx_messageInfo_Runtime_MinioConf proto.InternalMessageInfo

func (m *Runtime_MinioConf) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *Runtime_MinioConf) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type CreateRuntimeRequest struct {
	Runtime              *Runtime `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuntimeRequest) Reset()         { *m = CreateRuntimeRequest{} }
func (m *CreateRuntimeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRuntimeRequest) ProtoMessage()    {}
func (*CreateRuntimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{1}
}

func (m *CreateRuntimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuntimeRequest.Unmarshal(m, b)
}
func (m *CreateRuntimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuntimeRequest.Marshal(b, m, deterministic)
}
func (m *CreateRuntimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuntimeRequest.Merge(m, src)
}
func (m *CreateRuntimeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRuntimeRequest.Size(m)
}
func (m *CreateRuntimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuntimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuntimeRequest proto.InternalMessageInfo

func (m *CreateRuntimeRequest) GetRuntime() *Runtime {
	if m != nil {
		return m.Runtime
	}
	return nil
}

type CreateRuntimeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuntimeResponse) Reset()         { *m = CreateRuntimeResponse{} }
func (m *CreateRuntimeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRuntimeResponse) ProtoMessage()    {}
func (*CreateRuntimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{2}
}

func (m *CreateRuntimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuntimeResponse.Unmarshal(m, b)
}
func (m *CreateRuntimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuntimeResponse.Marshal(b, m, deterministic)
}
func (m *CreateRuntimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuntimeResponse.Merge(m, src)
}
func (m *CreateRuntimeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRuntimeResponse.Size(m)
}
func (m *CreateRuntimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuntimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuntimeResponse proto.InternalMessageInfo

func (m *CreateRuntimeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateRuntimeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Runtime)(nil), "runtime.Runtime")
	proto.RegisterType((*Runtime_MongoConf)(nil), "runtime.Runtime.MongoConf")
	proto.RegisterType((*Runtime_MinioConf)(nil), "runtime.Runtime.MinioConf")
	proto.RegisterType((*CreateRuntimeRequest)(nil), "runtime.CreateRuntimeRequest")
	proto.RegisterType((*CreateRuntimeResponse)(nil), "runtime.CreateRuntimeResponse")
}

func init() { proto.RegisterFile("runtimepb/runtime.proto", fileDescriptor_d0e5095094a8d27f) }

var fileDescriptor_d0e5095094a8d27f = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x6d, 0xfd, 0x93, 0xee, 0x04, 0x45, 0x16, 0xc5, 0x10, 0x54, 0x4a, 0x4e, 0xc5, 0x43,
	0x94, 0xf8, 0x0d, 0x9a, 0x83, 0x87, 0x22, 0xc8, 0x7a, 0xf3, 0x96, 0xc4, 0xb1, 0xe4, 0x90, 0xdd,
	0xb8, 0x93, 0x28, 0x7e, 0x0a, 0xbf, 0xb2, 0xec, 0x66, 0xb3, 0xd5, 0x62, 0x6f, 0xf3, 0xe6, 0xe5,
	0x3d, 0x7e, 0x59, 0x06, 0x2e, 0x74, 0x2f, 0xbb, 0xba, 0xc1, 0xb6, 0xbc, 0x75, 0x53, 0xda, 0x6a,
	0xd5, 0x29, 0x1e, 0x38, 0x99, 0x7c, 0x4f, 0x21, 0x10, 0xc3, 0xcc, 0x39, 0x1c, 0xc8, 0xa2, 0xc1,
	0x68, 0x32, 0x9f, 0x2c, 0x98, 0xb0, 0x33, 0xbf, 0x83, 0xc3, 0xa6, 0x96, 0xb5, 0x8a, 0xa6, 0xf3,
	0xc9, 0x22, 0xcc, 0xe2, 0x74, 0xec, 0x71, 0xa1, 0xf4, 0xd1, 0xb8, 0xb9, 0x92, 0x6f, 0x62, 0xf8,
	0xd0, 0x26, 0x94, 0x5c, 0xab, 0x68, 0x7f, 0x57, 0xc2, 0xb8, 0x2e, 0x61, 0xc6, 0x38, 0x07, 0xe6,
	0x77, 0x3c, 0x86, 0x59, 0x4f, 0xa8, 0x7f, 0x81, 0x78, 0x6d, 0xbc, 0xb6, 0x20, 0xfa, 0x54, 0xfa,
	0xd5, 0xf2, 0x30, 0xe1, 0x75, 0xfc, 0x00, 0xcc, 0xa3, 0xf0, 0x4b, 0x60, 0x45, 0x55, 0x21, 0xd1,
	0x0a, 0xbf, 0x5c, 0xcb, 0x66, 0x61, 0x5c, 0xc2, 0x4a, 0x63, 0x67, 0xdc, 0xa1, 0x67, 0xb3, 0x48,
	0x96, 0x70, 0x96, 0x6b, 0x2c, 0x3a, 0x74, 0xbc, 0x02, 0xdf, 0x7b, 0xa4, 0x8e, 0xdf, 0xc0, 0xf8,
	0x68, 0xb6, 0x31, 0xcc, 0x4e, 0xb7, 0xff, 0x4c, 0xf8, 0x57, 0x5d, 0xc1, 0xf9, 0x56, 0x07, 0xb5,
	0x4a, 0x12, 0xf2, 0x08, 0x02, 0xea, 0x2d, 0x88, 0x2d, 0x99, 0x89, 0x51, 0x1a, 0xa7, 0x41, 0xa2,
	0x62, 0x8d, 0x0e, 0x69, 0x94, 0x59, 0x09, 0x27, 0xae, 0xe6, 0x19, 0xf5, 0x47, 0x5d, 0x21, 0x7f,
	0x82, 0xe3, 0x3f, 0xf5, 0xfc, 0xca, 0xa3, 0xfc, 0x87, 0x1e, 0x5f, 0xef, 0xb2, 0x07, 0xaa, 0x64,
	0x6f, 0x19, 0xbe, 0x30, 0x7f, 0x2a, 0xe5, 0x91, 0xbd, 0x91, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x97, 0x56, 0x48, 0x20, 0x3e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuntimeServiceClient interface {
	CreateRuntime(ctx context.Context, in *CreateRuntimeRequest, opts ...grpc.CallOption) (*CreateRuntimeResponse, error)
}

type runtimeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRuntimeServiceClient(cc *grpc.ClientConn) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) CreateRuntime(ctx context.Context, in *CreateRuntimeRequest, opts ...grpc.CallOption) (*CreateRuntimeResponse, error) {
	out := new(CreateRuntimeResponse)
	err := c.cc.Invoke(ctx, "/runtime.RuntimeService/CreateRuntime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServiceServer is the server API for RuntimeService service.
type RuntimeServiceServer interface {
	CreateRuntime(context.Context, *CreateRuntimeRequest) (*CreateRuntimeResponse, error)
}

// UnimplementedRuntimeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRuntimeServiceServer struct {
}

func (*UnimplementedRuntimeServiceServer) CreateRuntime(ctx context.Context, req *CreateRuntimeRequest) (*CreateRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRuntime not implemented")
}

func RegisterRuntimeServiceServer(s *grpc.Server, srv RuntimeServiceServer) {
	s.RegisterService(&_RuntimeService_serviceDesc, srv)
}

func _RuntimeService_CreateRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).CreateRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runtime.RuntimeService/CreateRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).CreateRuntime(ctx, req.(*CreateRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RuntimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRuntime",
			Handler:    _RuntimeService_CreateRuntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtimepb/runtime.proto",
}
