{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else if .Capabilities.APIVersions.Has "extensions/v1beta1" }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ template "kre.fullname" . }}-admin-ui-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: {{ template "kre.fullname" . }}-admin-ui
    {{ if hasKey .Values.certManager "dns01" -}}
    cert-manager.io/acme-challenge-type: "dns01"
    {{ else -}}
    cert-manager.io/acme-challenge-type: "http01"
    {{ end }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app:  {{ template "kre.fullname" . }}-admin-ui-ingress
spec:
  {{- if .Values.adminUI.tls.enabled }}
  tls:
  - hosts: 
    - {{ .Values.adminUI.host }}
    secretName: {{ .Values.adminUI.host }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.adminUI.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: admin-ui
              servicePort: web
