// Code generated by protoc-gen-go. DO NOT EDIT.
// source: runtimepb/runtime.proto

package runtimepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entrypoint struct {
	ProtoFile            string   `protobuf:"bytes,1,opt,name=proto_file,json=protoFile,proto3" json:"proto_file,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Src                  string   `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entrypoint) Reset()         { *m = Entrypoint{} }
func (m *Entrypoint) String() string { return proto.CompactTextString(m) }
func (*Entrypoint) ProtoMessage()    {}
func (*Entrypoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{0}
}

func (m *Entrypoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entrypoint.Unmarshal(m, b)
}
func (m *Entrypoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entrypoint.Marshal(b, m, deterministic)
}
func (m *Entrypoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entrypoint.Merge(m, src)
}
func (m *Entrypoint) XXX_Size() int {
	return xxx_messageInfo_Entrypoint.Size(m)
}
func (m *Entrypoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Entrypoint.DiscardUnknown(m)
}

var xxx_messageInfo_Entrypoint proto.InternalMessageInfo

func (m *Entrypoint) GetProtoFile() string {
	if m != nil {
		return m.ProtoFile
	}
	return ""
}

func (m *Entrypoint) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Entrypoint) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Workflow struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Entrypoint           string           `protobuf:"bytes,2,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Nodes                []*Workflow_Node `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges                []*Workflow_Edge `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Workflow) Reset()         { *m = Workflow{} }
func (m *Workflow) String() string { return proto.CompactTextString(m) }
func (*Workflow) ProtoMessage()    {}
func (*Workflow) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{1}
}

func (m *Workflow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workflow.Unmarshal(m, b)
}
func (m *Workflow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workflow.Marshal(b, m, deterministic)
}
func (m *Workflow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workflow.Merge(m, src)
}
func (m *Workflow) XXX_Size() int {
	return xxx_messageInfo_Workflow.Size(m)
}
func (m *Workflow) XXX_DiscardUnknown() {
	xxx_messageInfo_Workflow.DiscardUnknown(m)
}

var xxx_messageInfo_Workflow proto.InternalMessageInfo

func (m *Workflow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Workflow) GetEntrypoint() string {
	if m != nil {
		return m.Entrypoint
	}
	return ""
}

func (m *Workflow) GetNodes() []*Workflow_Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Workflow) GetEdges() []*Workflow_Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

type Workflow_Node struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image,omitempty"`
	Src                  string   `protobuf:"bytes,4,opt,name=Src,proto3" json:"Src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Workflow_Node) Reset()         { *m = Workflow_Node{} }
func (m *Workflow_Node) String() string { return proto.CompactTextString(m) }
func (*Workflow_Node) ProtoMessage()    {}
func (*Workflow_Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{1, 0}
}

func (m *Workflow_Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workflow_Node.Unmarshal(m, b)
}
func (m *Workflow_Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workflow_Node.Marshal(b, m, deterministic)
}
func (m *Workflow_Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workflow_Node.Merge(m, src)
}
func (m *Workflow_Node) XXX_Size() int {
	return xxx_messageInfo_Workflow_Node.Size(m)
}
func (m *Workflow_Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Workflow_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Workflow_Node proto.InternalMessageInfo

func (m *Workflow_Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Workflow_Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Workflow_Node) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Workflow_Node) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Workflow_Edge struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FromNode             string   `protobuf:"bytes,2,opt,name=FromNode,proto3" json:"FromNode,omitempty"`
	ToNode               string   `protobuf:"bytes,3,opt,name=ToNode,proto3" json:"ToNode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Workflow_Edge) Reset()         { *m = Workflow_Edge{} }
func (m *Workflow_Edge) String() string { return proto.CompactTextString(m) }
func (*Workflow_Edge) ProtoMessage()    {}
func (*Workflow_Edge) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{1, 1}
}

func (m *Workflow_Edge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workflow_Edge.Unmarshal(m, b)
}
func (m *Workflow_Edge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workflow_Edge.Marshal(b, m, deterministic)
}
func (m *Workflow_Edge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workflow_Edge.Merge(m, src)
}
func (m *Workflow_Edge) XXX_Size() int {
	return xxx_messageInfo_Workflow_Edge.Size(m)
}
func (m *Workflow_Edge) XXX_DiscardUnknown() {
	xxx_messageInfo_Workflow_Edge.DiscardUnknown(m)
}

var xxx_messageInfo_Workflow_Edge proto.InternalMessageInfo

func (m *Workflow_Edge) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Workflow_Edge) GetFromNode() string {
	if m != nil {
		return m.FromNode
	}
	return ""
}

func (m *Workflow_Edge) GetToNode() string {
	if m != nil {
		return m.ToNode
	}
	return ""
}

type Version struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Entrypoint           *Entrypoint       `protobuf:"bytes,2,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Config               []*Version_Config `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty"`
	Workflows            []*Workflow       `protobuf:"bytes,4,rep,name=workflows,proto3" json:"workflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{2}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Version) GetEntrypoint() *Entrypoint {
	if m != nil {
		return m.Entrypoint
	}
	return nil
}

func (m *Version) GetConfig() []*Version_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Version) GetWorkflows() []*Workflow {
	if m != nil {
		return m.Workflows
	}
	return nil
}

type Version_Config struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version_Config) Reset()         { *m = Version_Config{} }
func (m *Version_Config) String() string { return proto.CompactTextString(m) }
func (*Version_Config) ProtoMessage()    {}
func (*Version_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{2, 0}
}

func (m *Version_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version_Config.Unmarshal(m, b)
}
func (m *Version_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version_Config.Marshal(b, m, deterministic)
}
func (m *Version_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version_Config.Merge(m, src)
}
func (m *Version_Config) XXX_Size() int {
	return xxx_messageInfo_Version_Config.Size(m)
}
func (m *Version_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Version_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Version_Config proto.InternalMessageInfo

func (m *Version_Config) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Version_Config) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DeployVersionRequest struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployVersionRequest) Reset()         { *m = DeployVersionRequest{} }
func (m *DeployVersionRequest) String() string { return proto.CompactTextString(m) }
func (*DeployVersionRequest) ProtoMessage()    {}
func (*DeployVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{3}
}

func (m *DeployVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployVersionRequest.Unmarshal(m, b)
}
func (m *DeployVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployVersionRequest.Marshal(b, m, deterministic)
}
func (m *DeployVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployVersionRequest.Merge(m, src)
}
func (m *DeployVersionRequest) XXX_Size() int {
	return xxx_messageInfo_DeployVersionRequest.Size(m)
}
func (m *DeployVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployVersionRequest proto.InternalMessageInfo

func (m *DeployVersionRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type DeployVersionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployVersionResponse) Reset()         { *m = DeployVersionResponse{} }
func (m *DeployVersionResponse) String() string { return proto.CompactTextString(m) }
func (*DeployVersionResponse) ProtoMessage()    {}
func (*DeployVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{4}
}

func (m *DeployVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployVersionResponse.Unmarshal(m, b)
}
func (m *DeployVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployVersionResponse.Marshal(b, m, deterministic)
}
func (m *DeployVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployVersionResponse.Merge(m, src)
}
func (m *DeployVersionResponse) XXX_Size() int {
	return xxx_messageInfo_DeployVersionResponse.Size(m)
}
func (m *DeployVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployVersionResponse proto.InternalMessageInfo

func (m *DeployVersionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeployVersionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateVersionConfigRequest struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateVersionConfigRequest) Reset()         { *m = UpdateVersionConfigRequest{} }
func (m *UpdateVersionConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateVersionConfigRequest) ProtoMessage()    {}
func (*UpdateVersionConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{5}
}

func (m *UpdateVersionConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVersionConfigRequest.Unmarshal(m, b)
}
func (m *UpdateVersionConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVersionConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateVersionConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVersionConfigRequest.Merge(m, src)
}
func (m *UpdateVersionConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateVersionConfigRequest.Size(m)
}
func (m *UpdateVersionConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVersionConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVersionConfigRequest proto.InternalMessageInfo

func (m *UpdateVersionConfigRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type UpdateVersionConfigResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateVersionConfigResponse) Reset()         { *m = UpdateVersionConfigResponse{} }
func (m *UpdateVersionConfigResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateVersionConfigResponse) ProtoMessage()    {}
func (*UpdateVersionConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{6}
}

func (m *UpdateVersionConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVersionConfigResponse.Unmarshal(m, b)
}
func (m *UpdateVersionConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVersionConfigResponse.Marshal(b, m, deterministic)
}
func (m *UpdateVersionConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVersionConfigResponse.Merge(m, src)
}
func (m *UpdateVersionConfigResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateVersionConfigResponse.Size(m)
}
func (m *UpdateVersionConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVersionConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVersionConfigResponse proto.InternalMessageInfo

func (m *UpdateVersionConfigResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateVersionConfigResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StopVersionRequest struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopVersionRequest) Reset()         { *m = StopVersionRequest{} }
func (m *StopVersionRequest) String() string { return proto.CompactTextString(m) }
func (*StopVersionRequest) ProtoMessage()    {}
func (*StopVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{7}
}

func (m *StopVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopVersionRequest.Unmarshal(m, b)
}
func (m *StopVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopVersionRequest.Marshal(b, m, deterministic)
}
func (m *StopVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopVersionRequest.Merge(m, src)
}
func (m *StopVersionRequest) XXX_Size() int {
	return xxx_messageInfo_StopVersionRequest.Size(m)
}
func (m *StopVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopVersionRequest proto.InternalMessageInfo

func (m *StopVersionRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type StopVersionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopVersionResponse) Reset()         { *m = StopVersionResponse{} }
func (m *StopVersionResponse) String() string { return proto.CompactTextString(m) }
func (*StopVersionResponse) ProtoMessage()    {}
func (*StopVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{8}
}

func (m *StopVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopVersionResponse.Unmarshal(m, b)
}
func (m *StopVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopVersionResponse.Marshal(b, m, deterministic)
}
func (m *StopVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopVersionResponse.Merge(m, src)
}
func (m *StopVersionResponse) XXX_Size() int {
	return xxx_messageInfo_StopVersionResponse.Size(m)
}
func (m *StopVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopVersionResponse proto.InternalMessageInfo

func (m *StopVersionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *StopVersionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeactivateVersionRequest struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeactivateVersionRequest) Reset()         { *m = DeactivateVersionRequest{} }
func (m *DeactivateVersionRequest) String() string { return proto.CompactTextString(m) }
func (*DeactivateVersionRequest) ProtoMessage()    {}
func (*DeactivateVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{9}
}

func (m *DeactivateVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeactivateVersionRequest.Unmarshal(m, b)
}
func (m *DeactivateVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeactivateVersionRequest.Marshal(b, m, deterministic)
}
func (m *DeactivateVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeactivateVersionRequest.Merge(m, src)
}
func (m *DeactivateVersionRequest) XXX_Size() int {
	return xxx_messageInfo_DeactivateVersionRequest.Size(m)
}
func (m *DeactivateVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeactivateVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeactivateVersionRequest proto.InternalMessageInfo

func (m *DeactivateVersionRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type DeactivateVersionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeactivateVersionResponse) Reset()         { *m = DeactivateVersionResponse{} }
func (m *DeactivateVersionResponse) String() string { return proto.CompactTextString(m) }
func (*DeactivateVersionResponse) ProtoMessage()    {}
func (*DeactivateVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{10}
}

func (m *DeactivateVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeactivateVersionResponse.Unmarshal(m, b)
}
func (m *DeactivateVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeactivateVersionResponse.Marshal(b, m, deterministic)
}
func (m *DeactivateVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeactivateVersionResponse.Merge(m, src)
}
func (m *DeactivateVersionResponse) XXX_Size() int {
	return xxx_messageInfo_DeactivateVersionResponse.Size(m)
}
func (m *DeactivateVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeactivateVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeactivateVersionResponse proto.InternalMessageInfo

func (m *DeactivateVersionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeactivateVersionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ActivateVersionRequest struct {
	Version              *Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateVersionRequest) Reset()         { *m = ActivateVersionRequest{} }
func (m *ActivateVersionRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateVersionRequest) ProtoMessage()    {}
func (*ActivateVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{11}
}

func (m *ActivateVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateVersionRequest.Unmarshal(m, b)
}
func (m *ActivateVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateVersionRequest.Marshal(b, m, deterministic)
}
func (m *ActivateVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateVersionRequest.Merge(m, src)
}
func (m *ActivateVersionRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateVersionRequest.Size(m)
}
func (m *ActivateVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateVersionRequest proto.InternalMessageInfo

func (m *ActivateVersionRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type ActivateVersionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateVersionResponse) Reset()         { *m = ActivateVersionResponse{} }
func (m *ActivateVersionResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateVersionResponse) ProtoMessage()    {}
func (*ActivateVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{12}
}

func (m *ActivateVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateVersionResponse.Unmarshal(m, b)
}
func (m *ActivateVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateVersionResponse.Marshal(b, m, deterministic)
}
func (m *ActivateVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateVersionResponse.Merge(m, src)
}
func (m *ActivateVersionResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateVersionResponse.Size(m)
}
func (m *ActivateVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateVersionResponse proto.InternalMessageInfo

func (m *ActivateVersionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ActivateVersionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Entrypoint)(nil), "runtime.Entrypoint")
	proto.RegisterType((*Workflow)(nil), "runtime.Workflow")
	proto.RegisterType((*Workflow_Node)(nil), "runtime.Workflow.Node")
	proto.RegisterType((*Workflow_Edge)(nil), "runtime.Workflow.Edge")
	proto.RegisterType((*Version)(nil), "runtime.Version")
	proto.RegisterType((*Version_Config)(nil), "runtime.Version.Config")
	proto.RegisterType((*DeployVersionRequest)(nil), "runtime.DeployVersionRequest")
	proto.RegisterType((*DeployVersionResponse)(nil), "runtime.DeployVersionResponse")
	proto.RegisterType((*UpdateVersionConfigRequest)(nil), "runtime.UpdateVersionConfigRequest")
	proto.RegisterType((*UpdateVersionConfigResponse)(nil), "runtime.UpdateVersionConfigResponse")
	proto.RegisterType((*StopVersionRequest)(nil), "runtime.StopVersionRequest")
	proto.RegisterType((*StopVersionResponse)(nil), "runtime.StopVersionResponse")
	proto.RegisterType((*DeactivateVersionRequest)(nil), "runtime.DeactivateVersionRequest")
	proto.RegisterType((*DeactivateVersionResponse)(nil), "runtime.DeactivateVersionResponse")
	proto.RegisterType((*ActivateVersionRequest)(nil), "runtime.ActivateVersionRequest")
	proto.RegisterType((*ActivateVersionResponse)(nil), "runtime.ActivateVersionResponse")
}

func init() { proto.RegisterFile("runtimepb/runtime.proto", fileDescriptor_d0e5095094a8d27f) }

var fileDescriptor_d0e5095094a8d27f = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xeb, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0x72, 0x69, 0x2e, 0x13, 0x7d, 0xa5, 0xdd, 0x94, 0xc4, 0xb8, 0xb4, 0x04, 0xc3, 0x8f,
	0x0a, 0xa1, 0x04, 0xa5, 0x2f, 0x40, 0x4b, 0x1a, 0x91, 0x22, 0x0a, 0x38, 0x50, 0x24, 0x84, 0x84,
	0x12, 0x7b, 0x12, 0x59, 0x4d, 0xbc, 0xc6, 0xeb, 0xa4, 0xca, 0xab, 0xf1, 0x04, 0x3c, 0x09, 0xcf,
	0x81, 0xf6, 0xe2, 0xcd, 0xcd, 0xe9, 0x8f, 0x86, 0x7f, 0x3b, 0x3b, 0x67, 0xce, 0x9c, 0x39, 0x3b,
	0x96, 0xa1, 0x1a, 0x4e, 0xfc, 0xc8, 0x1b, 0x63, 0xd0, 0x6f, 0xa8, 0x53, 0x3d, 0x08, 0x69, 0x44,
	0x49, 0x5e, 0x85, 0x56, 0x17, 0xe0, 0xc2, 0x8f, 0xc2, 0x59, 0x40, 0x3d, 0x3f, 0x22, 0x47, 0x00,
	0x22, 0xff, 0x63, 0xe0, 0x8d, 0xd0, 0x48, 0xd5, 0x52, 0x27, 0x45, 0xbb, 0x28, 0x6e, 0xda, 0xde,
	0x08, 0xc9, 0x01, 0xec, 0x78, 0xe3, 0xde, 0x10, 0x8d, 0xb4, 0xc8, 0xc8, 0x80, 0xec, 0x41, 0x86,
	0x85, 0x8e, 0x91, 0x11, 0x77, 0xfc, 0x68, 0xfd, 0x4a, 0x43, 0xe1, 0x2b, 0x0d, 0x6f, 0x06, 0x23,
	0x7a, 0x4b, 0x08, 0x64, 0xfd, 0xde, 0x38, 0x66, 0x13, 0x67, 0x72, 0x0c, 0x80, 0xba, 0xab, 0x62,
	0x5b, 0xb8, 0x21, 0x2f, 0x61, 0xc7, 0xa7, 0x2e, 0x32, 0x23, 0x53, 0xcb, 0x9c, 0x94, 0x9a, 0x95,
	0x7a, 0xac, 0x3e, 0x66, 0xad, 0x5f, 0x51, 0x17, 0x6d, 0x09, 0xe2, 0x68, 0x74, 0x87, 0xc8, 0x8c,
	0xec, 0x26, 0xf4, 0x85, 0x3b, 0x44, 0x5b, 0x82, 0x4c, 0x1b, 0xb2, 0xbc, 0x98, 0xec, 0x42, 0xba,
	0xe3, 0x2a, 0x55, 0xe9, 0x8e, 0xcb, 0x75, 0x5e, 0x71, 0x9d, 0x52, 0x8d, 0x38, 0xf3, 0x81, 0x3b,
	0x62, 0x60, 0x39, 0x9c, 0x0c, 0xf8, 0xc0, 0xdd, 0xd0, 0x31, 0xb2, 0x72, 0xe0, 0x6e, 0xe8, 0x98,
	0x97, 0x90, 0xe5, 0x2d, 0xd6, 0x38, 0x4d, 0x28, 0xb4, 0x43, 0x3a, 0xe6, 0xfd, 0x14, 0xaf, 0x8e,
	0x49, 0x05, 0x72, 0x9f, 0xa9, 0xc8, 0x48, 0x72, 0x15, 0x59, 0x7f, 0x52, 0x90, 0xbf, 0xc6, 0x90,
	0x79, 0xd4, 0x4f, 0xf4, 0xee, 0x74, 0xcd, 0xbb, 0x52, 0xb3, 0xac, 0x47, 0x9e, 0x3f, 0xe6, 0x92,
	0xa1, 0x0d, 0xc8, 0x39, 0xd4, 0x1f, 0x78, 0x43, 0xe5, 0x68, 0x55, 0x17, 0xa8, 0x56, 0xf5, 0x37,
	0x22, 0x6d, 0x2b, 0x18, 0x69, 0x40, 0xf1, 0x56, 0xb9, 0x17, 0xfb, 0xba, 0xbf, 0xe6, 0xab, 0x3d,
	0xc7, 0x98, 0xaf, 0x20, 0x27, 0x29, 0xb8, 0x3d, 0x37, 0x38, 0x53, 0x9a, 0xf9, 0x91, 0xdb, 0x38,
	0xed, 0x8d, 0x26, 0x7a, 0x6f, 0x44, 0x60, 0x9d, 0xc3, 0x41, 0x0b, 0x83, 0x11, 0x9d, 0x29, 0x09,
	0x36, 0xfe, 0x9c, 0x20, 0x8b, 0xc8, 0x0b, 0xc8, 0x4f, 0xe5, 0x8d, 0xe0, 0x28, 0x35, 0xf7, 0x56,
	0xc5, 0xda, 0x31, 0xc0, 0x7a, 0x07, 0x0f, 0x57, 0x38, 0x58, 0x40, 0x7d, 0x86, 0xc4, 0x80, 0x3c,
	0x9b, 0x38, 0x0e, 0x32, 0x26, 0x48, 0x0a, 0x76, 0x1c, 0xf2, 0xcc, 0x18, 0x19, 0x9b, 0xaf, 0x71,
	0x1c, 0x5a, 0x6f, 0xc1, 0xfc, 0x12, 0xb8, 0xbd, 0x08, 0x15, 0x99, 0xb2, 0xe4, 0x1e, 0xb2, 0x3e,
	0xc1, 0x61, 0x22, 0xd3, 0x16, 0xe2, 0x5e, 0x03, 0xe9, 0x46, 0x34, 0xd8, 0xc2, 0xab, 0x0e, 0x94,
	0x97, 0x18, 0xb6, 0x10, 0xd3, 0x06, 0xa3, 0x85, 0x3d, 0x27, 0xf2, 0xa6, 0xf3, 0x19, 0xef, 0x23,
	0xe9, 0x03, 0x3c, 0x4a, 0xe0, 0xd9, 0x42, 0x58, 0x0b, 0x2a, 0x67, 0xdb, 0xcb, 0x7a, 0x0f, 0xd5,
	0xb3, 0x7f, 0x27, 0xaa, 0xf9, 0x3b, 0x03, 0xbb, 0xb6, 0xec, 0xd5, 0xc5, 0x70, 0xea, 0x39, 0x48,
	0x3e, 0xc2, 0xff, 0x4b, 0x7b, 0x4b, 0x8e, 0xb4, 0x9a, 0xa4, 0x6f, 0xc2, 0x3c, 0xde, 0x94, 0x96,
	0xb2, 0xac, 0xff, 0x48, 0x1f, 0xca, 0x09, 0x2b, 0x47, 0x9e, 0xe9, 0xc2, 0xcd, 0xab, 0x6d, 0x3e,
	0xbf, 0x1b, 0xa4, 0x7b, 0x5c, 0x42, 0x69, 0x61, 0x83, 0xc8, 0xa1, 0x2e, 0x5b, 0xdf, 0x4c, 0xf3,
	0x71, 0x72, 0x52, 0x73, 0x7d, 0x87, 0xfd, 0xb5, 0xa7, 0x27, 0x4f, 0x17, 0xc6, 0x4c, 0x5e, 0x2f,
	0xd3, 0xba, 0x0b, 0xa2, 0xd9, 0xaf, 0xe1, 0xc1, 0xca, 0x0b, 0x92, 0x27, 0xba, 0x30, 0x79, 0x43,
	0xcc, 0xda, 0x66, 0x40, 0xcc, 0x7b, 0x5e, 0xfa, 0x56, 0xd4, 0xbf, 0xd4, 0x7e, 0x4e, 0xfc, 0x19,
	0x4f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x14, 0x96, 0xd1, 0xd1, 0x66, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuntimeServiceClient interface {
	DeployVersion(ctx context.Context, in *DeployVersionRequest, opts ...grpc.CallOption) (*DeployVersionResponse, error)
	UpdateVersionConfig(ctx context.Context, in *UpdateVersionConfigRequest, opts ...grpc.CallOption) (*UpdateVersionConfigResponse, error)
	StopVersion(ctx context.Context, in *StopVersionRequest, opts ...grpc.CallOption) (*StopVersionResponse, error)
	DeactivateVersion(ctx context.Context, in *DeactivateVersionRequest, opts ...grpc.CallOption) (*DeactivateVersionResponse, error)
	ActivateVersion(ctx context.Context, in *ActivateVersionRequest, opts ...grpc.CallOption) (*ActivateVersionResponse, error)
}

type runtimeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRuntimeServiceClient(cc *grpc.ClientConn) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) DeployVersion(ctx context.Context, in *DeployVersionRequest, opts ...grpc.CallOption) (*DeployVersionResponse, error) {
	out := new(DeployVersionResponse)
	err := c.cc.Invoke(ctx, "/runtime.RuntimeService/DeployVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) UpdateVersionConfig(ctx context.Context, in *UpdateVersionConfigRequest, opts ...grpc.CallOption) (*UpdateVersionConfigResponse, error) {
	out := new(UpdateVersionConfigResponse)
	err := c.cc.Invoke(ctx, "/runtime.RuntimeService/UpdateVersionConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) StopVersion(ctx context.Context, in *StopVersionRequest, opts ...grpc.CallOption) (*StopVersionResponse, error) {
	out := new(StopVersionResponse)
	err := c.cc.Invoke(ctx, "/runtime.RuntimeService/StopVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) DeactivateVersion(ctx context.Context, in *DeactivateVersionRequest, opts ...grpc.CallOption) (*DeactivateVersionResponse, error) {
	out := new(DeactivateVersionResponse)
	err := c.cc.Invoke(ctx, "/runtime.RuntimeService/DeactivateVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ActivateVersion(ctx context.Context, in *ActivateVersionRequest, opts ...grpc.CallOption) (*ActivateVersionResponse, error) {
	out := new(ActivateVersionResponse)
	err := c.cc.Invoke(ctx, "/runtime.RuntimeService/ActivateVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServiceServer is the server API for RuntimeService service.
type RuntimeServiceServer interface {
	DeployVersion(context.Context, *DeployVersionRequest) (*DeployVersionResponse, error)
	UpdateVersionConfig(context.Context, *UpdateVersionConfigRequest) (*UpdateVersionConfigResponse, error)
	StopVersion(context.Context, *StopVersionRequest) (*StopVersionResponse, error)
	DeactivateVersion(context.Context, *DeactivateVersionRequest) (*DeactivateVersionResponse, error)
	ActivateVersion(context.Context, *ActivateVersionRequest) (*ActivateVersionResponse, error)
}

// UnimplementedRuntimeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRuntimeServiceServer struct {
}

func (*UnimplementedRuntimeServiceServer) DeployVersion(ctx context.Context, req *DeployVersionRequest) (*DeployVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployVersion not implemented")
}
func (*UnimplementedRuntimeServiceServer) UpdateVersionConfig(ctx context.Context, req *UpdateVersionConfigRequest) (*UpdateVersionConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVersionConfig not implemented")
}
func (*UnimplementedRuntimeServiceServer) StopVersion(ctx context.Context, req *StopVersionRequest) (*StopVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVersion not implemented")
}
func (*UnimplementedRuntimeServiceServer) DeactivateVersion(ctx context.Context, req *DeactivateVersionRequest) (*DeactivateVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateVersion not implemented")
}
func (*UnimplementedRuntimeServiceServer) ActivateVersion(ctx context.Context, req *ActivateVersionRequest) (*ActivateVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateVersion not implemented")
}

func RegisterRuntimeServiceServer(s *grpc.Server, srv RuntimeServiceServer) {
	s.RegisterService(&_RuntimeService_serviceDesc, srv)
}

func _RuntimeService_DeployVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).DeployVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runtime.RuntimeService/DeployVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).DeployVersion(ctx, req.(*DeployVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_UpdateVersionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVersionConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).UpdateVersionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runtime.RuntimeService/UpdateVersionConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).UpdateVersionConfig(ctx, req.(*UpdateVersionConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_StopVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).StopVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runtime.RuntimeService/StopVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).StopVersion(ctx, req.(*StopVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_DeactivateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).DeactivateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runtime.RuntimeService/DeactivateVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).DeactivateVersion(ctx, req.(*DeactivateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ActivateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ActivateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runtime.RuntimeService/ActivateVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ActivateVersion(ctx, req.(*ActivateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RuntimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployVersion",
			Handler:    _RuntimeService_DeployVersion_Handler,
		},
		{
			MethodName: "UpdateVersionConfig",
			Handler:    _RuntimeService_UpdateVersionConfig_Handler,
		},
		{
			MethodName: "StopVersion",
			Handler:    _RuntimeService_StopVersion_Handler,
		},
		{
			MethodName: "DeactivateVersion",
			Handler:    _RuntimeService_DeactivateVersion_Handler,
		},
		{
			MethodName: "ActivateVersion",
			Handler:    _RuntimeService_ActivateVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtimepb/runtime.proto",
}
