dependencies:
  - name: mongodb-replicaset
    version: "3.11.3"
    repository: https://kubernetes-charts.storage.googleapis.com/
    alias: mongo
  - name: influxdb2
    version: "1.0.5"
    repository: https://influxdata.github.io/helm-charts
