dependencies:
  - name: mongodb-replicaset
    version: "3.11.3"
    repository: https://kubernetes-charts.storage.googleapis.com/
    alias: mongo
  - name: influxdb
    version: "4.8.1"
    repository: https://influxdata.github.io/helm-charts
