developmentMode: false

entrypoint:
  host: "local"

sharedStorageClass: standard

nats:
  enabled: true
  replicaCount: 3

  fullnameOverride: kre-nats
  auth:
    enabled: false
  cluster:
    enabled: true

  clusterAuth:
    enabled: false
  debug:
    enabled: true
    trace: true
    logtime: true
  metrics:
    enabled: true

mongo:
  replicas: 3
  replicaSetName: rs0
  image:
    tag: 4.2
  securityContext:
    enabled: false
  persistentVolume:
    enabled: true
    storageClass: standard
    size: 5Gi
  auth:
    enabled: true
    key: "qwerlk12SDf"
    adminUser: "admin"
    adminPassword: "123456"
  extraLabels:
    kre-app: kre-mongo

minio:
  credentials:
    accessKey: admin
    secretKey: "12345678"
  storage:
    size: 1Gi
