{{ if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
  {{ else if .Capabilities.APIVersions.Has "extensions/v1beta1" }}
apiVersion: extensions/v1beta1
  {{ end }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}-k8s-manager
  labels:
    {{- include "k8s-manager.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-manager.labels" . | nindent 8 }}
      annotations:
        helm.sh/restart-deployment: {{ randAlphaNum 5 | quote }}
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccount }}
      containers:
        - name: {{ .Release.Name }}-k8s-manager
          image: {{ .Values.k8sManager.image.repository }}:{{ .Values.k8sManager.image.tag }}
          imagePullPolicy: {{ .Values.k8sManager.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secrets

          env:
            - name: KRE_PORT
              value: "50051"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          ports:
            - containerPort: 50051
              protocol: TCP
              name: grpc
