{{ if .Values.rbac.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-manager
  labels:
    {{- include "k8s-manager.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: k8s-manager
    apiGroup: ""
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: kre-admin
  apiGroup: rbac.authorization.k8s.io
{{ end }}
