apiVersion: v1
kind: Service
metadata:
  name: k8s-manager
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-k8s-manager
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: grpc
  selector:
    app: {{ .Release.Name }}-k8s-manager
    release: {{ $.Release.Name | quote }}
