{{- if .Values.k8sManager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-manager.serviceAccountName" . }}
  labels:
    {{- include "k8s-manager.labels" . | nindent 4 }}
  {{- if .Values.k8sManager.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.k8sManager.serviceAccount.annotations | indent 4 }}
  {{- end }}
{{- end }}
