export enum ENDPOINT {
  SUBMIT_MAGIC_LINK = 'signin',
  VALIDATE_MAGIC_LINK = 'signin/verify',
  LOGOUT = 'logout'
}

export enum STATES {
  INITIALIZING = 'INITIALIZING',
  LOADING = 'LOADING',
  DISABLED = 'DISABLED',
  ERROR = 'ERROR',
  ALERT = 'ALERT',
  SUCCESS = 'SUCCESS',
  HOVER = 'HOVER',
  STARTING = 'STARTING',
  STARTED = 'STARTED',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  DEFAULT = 'DEFAULT',
}
