export const ENDPOINT = {
  SUBMIT_MAGIC_LINK: 'signin',
  VALIDATE_MAGIC_LINK: 'signin/verify',
  LOGOUT: 'logout'
};

export const STATES = {
  INITIALIZING: 'INITIALIZING',
  LOADING: 'LOADING',
  DISABLED: 'DISABLED',
  ERROR: 'ERROR',
  ALERT: 'ALERT',
  SUCCESS: 'SUCCESS',
  DEFAULT: 'DEFAULT',
  HOVER: 'HOVER',
  STARTING: 'STARTING',
  STARTED: 'STARTED',
  STOPPING: 'STOPPING',
  STOPPED: 'STOPPED'
};
