apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongoExpress.name" . }}
  labels:
    {{- include "mongoExpress.labels" . | nindent 4}}
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    {{- include "mongoExpress.selectorLabels" . | nindent 4 }}
