apiVersion: v1
kind: Service
metadata:
  name: kre-nats
  labels:
    {{- include "nats-streaming.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nats-streaming.selectorLabels" . | nindent 4}}
  ports:
    - name: nats
      protocol: TCP
      port: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
