apiVersion: v1
kind: Service
metadata:
  name: kre-mongo-express
  labels:
    {{ include "runtime.labels" . | nindent 4 }}
    app: kre-mongo-express
    kre-app: kre-mongo-express
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: kre-mongo-express
