apiVersion: v1
kind: Secret
metadata:
  name: kre-mongo-secret
  labels:
    app: kre-mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.engine.mongodb.rootCredentials.username | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.engine.mongodb.rootCredentials.password | b64enc }}
