{{ if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint
  annotations:
    {{ if and .Values.certManager.enabled .Values.entrypoint.tls }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ include "runtime.name" . }}-clusterissuer-runtimes-entrypoints
    {{ end }}
{{- if .Values.entrypoint.grpc.ingress.annotations }}
{{ toYaml .Values.entrypoint.grpc.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ template "runtime.fullname" . }}-entrypoint
spec:
  host: entrypoint.{{ .Values.entrypoint.host }}
  path: /  
  port:
    targetPort: grpc
  to:
    kind: Service
    name: active-entrypoint
    weight: 100
{{ else }}
{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if and .Values.certManager.enabled .Values.entrypoint.tls }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ include "runtime.name" . }}-clusterissuer-runtimes-entrypoints
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    # Based on this snippet:
    #  https://github.com/kubernetes/ingress-nginx/issues/5609#issuecomment-634908849
    nginx.ingress.kubernetes.io/server-snippet: |
      error_page 404 = @grpc_unimplemented;
      error_page 502 503 = @grpc_unavailable;

      location @grpc_unimplemented {
          add_header grpc-status 12;
          add_header grpc-message unimplemented;
          return 204;
      }
      location @grpc_unavailable {
          add_header grpc-status 14;
          add_header grpc-message unavailable;
          return 204;
      }
      default_type application/grpc;
{{- if .Values.entrypoint.grpc.ingress.annotations }}
{{ toYaml .Values.entrypoint.grpc.ingress.annotations | indent 4 }}
{{- end }}
spec:
  {{ if .Values.entrypoint.tls -}}
  tls:
    - hosts:
        - entrypoint.{{ .Values.entrypoint.host }}
      secretName: entrypoint.{{ .Values.entrypoint.host }}-tls
  {{ end -}}
  rules:
    - host: entrypoint.{{ .Values.entrypoint.host }}
      http:
        paths:
        {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: active-entrypoint
                port:
                  name: grpc
        {{ else }}
          - path: /
            backend:
              serviceName: active-entrypoint
              servicePort: grpc
        {{ end }}
{{ end }}
