{{ if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint
  annotations:
    {{ if and .Values.certManager.enabled .Values.entrypoint.tls }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ include "runtime.name" . }}-clusterissuer-runtimes-entrypoints
    {{ end }}
{{- if .Values.entrypoint.grpc.ingress.annotations }}
{{ toYaml .Values.entrypoint.grpc.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ template "runtime.fullname" . }}-entrypoint
spec:
  host: entrypoint.{{ .Values.entrypoint.host }}
  path: /  
  port:
    targetPort: grpc
  to:
    kind: Service
    name: active-entrypoint
    weight: 100
{{ else }}
{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint
  annotations:
    {{- include "kre-entrypoint.grpc.ingress.annotations" . | nindent 4 }}
spec:
  {{ if .Values.entrypoint.tls -}}
  tls:
    - hosts:
        - entrypoint.{{ .Values.entrypoint.host }}
      secretName: entrypoint.{{ .Values.entrypoint.host }}-tls
  {{ end -}}
  rules:
    - host: entrypoint.{{ .Values.entrypoint.host }}
      http:
        paths:
        {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: active-entrypoint
                port:
                  name: grpc
        {{ else }}
          - path: /
            backend:
              serviceName: active-entrypoint
              servicePort: grpc
        {{ end }}
{{ end }}
