{{ if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint-web
  annotations:
    {{ if .Values.entrypoint.tls }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ include "runtime.name" . }}-clusterissuer-runtimes-entrypoints
    {{ end }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ template "runtime.fullname" . }}-entrypoint-web
spec:
  host: proto.{{ .Values.entrypoint.host }}
  path: /  
  port:
    targetPort: web
  to:
    kind: Service
    name: active-entrypoint
    weight: 100
{{ else }}
{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint-web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{ if .Values.entrypoint.tls }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ include "runtime.name" . }}-clusterissuer-runtimes-entrypoints
    {{ end }}
    nginx.ingress.kubernetes.io/default-backend: runtime-default-backend
    nginx.ingress.kubernetes.io/custom-http-errors: "404,503,502"
spec:
  {{ if .Values.entrypoint.tls -}}
  tls:
    - hosts:
        - proto.{{ .Values.entrypoint.host }}
      secretName: proto.{{ .Values.entrypoint.host }}-tls
  {{ end -}}
  rules:
    - host: proto.{{ .Values.entrypoint.host }}
      http:
        paths:
        {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: active-entrypoint
                port:
                  name: web
        {{ else }}
          - path: /
            backend:
              serviceName: active-entrypoint
              servicePort: web
        {{ end }}
{{ end }}
