{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint-web
  annotations:
    {{- include "kre-entrypoint.ingress.annotations" . | nindent 4 }}
spec:
  {{ if .Values.entrypoint.tls -}}
  tls:
    - hosts:
        - proto.{{ .Values.entrypoint.host }}
      secretName: proto.{{ .Values.entrypoint.host }}-tls
  {{ end -}}
  rules:
    - host: proto.{{ .Values.entrypoint.host }}
      http:
        paths:
        {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: active-entrypoint
                port:
                  name: web
        {{ else }}
          - path: /
            backend:
              serviceName: active-entrypoint
              servicePort: web
        {{ end }}
