{{- if and .Values.entrypoint.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.entrypoint.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.entrypoint.ingress.annotations "kubernetes.io/ingress.class" .Values.entrypoint.ingress.className }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint-web
  {{- with .Values.entrypoint.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
spec:
  {{- if and .Values.entrypoint.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.entrypoint.ingress.className }}
  {{- end }}
  {{- if .Values.entrypoint.tls }}
  tls:
    - hosts:
        - proto.{{ .Values.entrypoint.host }}
      secretName: proto.{{ .Values.entrypoint.host }}-tls
  {{- end }}
  rules:
    - host: proto.{{ .Values.entrypoint.host }}
      http:
        paths:
          - path: "/"
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: active-entrypoint
                port:
                  name: web
              {{- else }}
              serviceName: active-entrypoint
              servicePort: web
              {{- end }}
