{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-entrypoint-web
  {{- with .Values.entrypoint.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kre.labels" . | nindent 4 }}
spec:
  {{- if .Values.entrypoint.tls }}
  tls:
    - hosts:
        - proto.{{ .Values.entrypoint.host }}
      secretName: proto.{{ .Values.entrypoint.host }}-tls
  {{- end }}
  rules:
    - host: proto.{{ .Values.entrypoint.host }}
      http:
        paths:
        {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: active-entrypoint
                port:
                  name: web
        {{- else }}
          - path: /
            backend:
              serviceName: active-entrypoint
              servicePort: web
        {{- end }}
