baseDomainName: "local"
releaseName: ""
application:
  versionStatusTimeout: 20m
admin:
  apiAddress: ":4000"
  baseURL: "http://api.kre.local"
  frontendBaseURL: "http://admin.kre.local"
  corsEnabled: true
  storagePath: /admin-api-files
smtp:
  enabled: false
auth:
  verificationCodeDurationInMinutes: 1
  jwtSignSecret: "jwt_secret"
  apiTokenSecret: "api_token_secret"
  secureCookie: false
  cookieDomain: "kre.local"
mongodb:
  address: "mongodb://admin:123456@localhost:27017/admin?replicaSet=rs0"
  dbName: "kre"
  runtimeDataUser: "kre-runtime-data"
  krtBucket: "krt"
influxdb:
  address: "http://localhost:8086"
chronograf:
  address: "http://localhost:8888"
k8s:
  namespace: ""
services:
  k8sManager: "localhost:50051"
runtime:
  name: ""
