// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import monitoringpb "github.com/konstellation-io/kre/runtime-api/proto/monitoringpb"

// MonitoringServiceServer is an autogenerated mock type for the MonitoringServiceServer type
type MonitoringServiceServer struct {
	mock.Mock
}

// NodeLogs provides a mock function with given fields: _a0, _a1
func (_m *MonitoringServiceServer) NodeLogs(_a0 *monitoringpb.NodeLogsRequest, _a1 monitoringpb.MonitoringService_NodeLogsServer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*monitoringpb.NodeLogsRequest, monitoringpb.MonitoringService_NodeLogsServer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NodeStatus provides a mock function with given fields: _a0, _a1
func (_m *MonitoringServiceServer) NodeStatus(_a0 *monitoringpb.NodeStatusRequest, _a1 monitoringpb.MonitoringService_NodeStatusServer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*monitoringpb.NodeStatusRequest, monitoringpb.MonitoringService_NodeStatusServer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
