// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "gitlab.com/konstellation/konstellation-ce/kre/runtime-api/domain/entity"
import mock "github.com/stretchr/testify/mock"

// ResourceManagerService is an autogenerated mock type for the ResourceManagerService type
type ResourceManagerService struct {
	mock.Mock
}

// ActivateVersion provides a mock function with given fields: name
func (_m *ResourceManagerService) ActivateVersion(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateEntrypoint provides a mock function with given fields: version
func (_m *ResourceManagerService) CreateEntrypoint(version *entity.Version) error {
	ret := _m.Called(version)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Version) error); ok {
		r0 = rf(version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateNode provides a mock function with given fields: version, node
func (_m *ResourceManagerService) CreateNode(version *entity.Version, node *entity.Node) error {
	ret := _m.Called(version, node)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Version, *entity.Node) error); ok {
		r0 = rf(version, node)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeactivateVersion provides a mock function with given fields: name
func (_m *ResourceManagerService) DeactivateVersion(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StopVersion provides a mock function with given fields: name
func (_m *ResourceManagerService) StopVersion(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
