apiVersion: v1
kind: ConfigMap
metadata:
  name: chronograf-config
  labels:
    {{ include "runtime.labels" . | nindent 4 }}
    app: chronograf
data:
  kre_conn.src: |-
    {
      "id": "10000",
      "name": "Runtime InfluxDB",
      "username": "",
      "password": "",
      "url": "http://{{ .Release.Name }}-influxdb:8086",
      "type": "influx",
      "insecureSkipVerify": false,
      "default": true,
      "telegraf": "telegraf",
      "organization": "kre"
    }
