apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nats-manager
  labels:
    {{- include "nats-manager.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: grpc
  selector:
    {{- include "nats-manager.selectorLabels" . | nindent 4 }}
