apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-default-backend-config
  labels:
    {{ include "runtime.labels" . | nindent 4 }}
    app: runtime-default-backend
data:

  index.html: |-
    <html>
        <body>No published entrypoint for this runtime.</body>
    </html>
