apiVersion: v1
kind: Service
metadata:
  name: runtime-default-backend
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
    app: runtime-default-backend
spec:
  clusterIP: None
  ports:
    - name: static
      port: 80
      protocol: TCP
      targetPort: static

  selector:
    {{- include "runtime.labels" . | nindent 4 }}
    app: runtime-default-backend
