linters:
  enable-all: true
  disable:
    - gomnd
    - funlen # TODO: enable and refactor long functions
    - nestif # TODO: enable and refactor nested ifs

# all available settings of specific linters
linters-settings:
  unparam:
    check-exported: true
  funlen:
    lines: 120
    statements: 80
  misspell:
    ignore-words:
      - konstellation
