{{ if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
  {{ else if .Capabilities.APIVersions.Has "extensions/v1beta1" }}
apiVersion: extensions/v1beta1
  {{ end }}
kind: Deployment
metadata:
  name: chronograf
  labels:
    {{- include "chronograf.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chronograf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/engine/chronograf/config.yml") . | sha256sum }}
      labels:
        {{- include "chronograf.labels" . | nindent 8 }}
    spec:
      containers:
        - name: chronograf
          image: "chronograf:1.8.4"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              name: api
          volumeMounts:
            - name: data
              mountPath: /var/lib/chronograf
            - name: config
              mountPath: /usr/share/chronograf/resources
          env:
            - name: RESOURCES_PATH
              value: /usr/share/chronograf/resources
            - name: BASE_PATH
              value: /measurements/{{ .Release.Namespace }}
            - name: STATUS_FEED_URL
              value: ""
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-chronograf-pvc
        - name: config
          configMap:
            name: chronograf-config
