apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-chronograf-pvc
  labels:
    {{- include "chronograf.labels" . | nindent 4 }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.chronograf.persistence.storageClass }}
spec:
  accessModes:
    - {{ .Values.chronograf.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.chronograf.persistence.size }}
