apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chronograf
  labels:
    {{- include "chronograf.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8888
      name: server
  selector:
    {{- include "chronograf.selectorLabels" . | nindent 4 }}
