apiVersion: v1
kind: Service
metadata:
  name: chronograf
  labels: {{- include "chronograf.labels" . }}
spec:
  ports:
    - port: 80
      targetPort: 8888
      name: server
  selector:
    {{- include "chronograf.selectorLabels" . }}
