apiVersion: v1
kind: Service
metadata:
  name: runtime-api
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
    app: runtime-api
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: grpc
  selector:
    {{- include "runtime.labels" . | nindent 4 }}
    app: runtime-api
