// Code generated by protoc-gen-go. DO NOT EDIT.
// source: runtimepb/runtime.proto

package runtimepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RuntimeVersion struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuntimeVersion) Reset()         { *m = RuntimeVersion{} }
func (m *RuntimeVersion) String() string { return proto.CompactTextString(m) }
func (*RuntimeVersion) ProtoMessage()    {}
func (*RuntimeVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{0}
}

func (m *RuntimeVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeVersion.Unmarshal(m, b)
}
func (m *RuntimeVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeVersion.Marshal(b, m, deterministic)
}
func (m *RuntimeVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeVersion.Merge(m, src)
}
func (m *RuntimeVersion) XXX_Size() int {
	return xxx_messageInfo_RuntimeVersion.Size(m)
}
func (m *RuntimeVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeVersion.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeVersion proto.InternalMessageInfo

func (m *RuntimeVersion) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RuntimeVersion) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRuntimeVersionRequest struct {
	RuntimeVersion       *RuntimeVersion `protobuf:"bytes,1,opt,name=runtimeVersion,proto3" json:"runtimeVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateRuntimeVersionRequest) Reset()         { *m = CreateRuntimeVersionRequest{} }
func (m *CreateRuntimeVersionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRuntimeVersionRequest) ProtoMessage()    {}
func (*CreateRuntimeVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{1}
}

func (m *CreateRuntimeVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuntimeVersionRequest.Unmarshal(m, b)
}
func (m *CreateRuntimeVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuntimeVersionRequest.Marshal(b, m, deterministic)
}
func (m *CreateRuntimeVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuntimeVersionRequest.Merge(m, src)
}
func (m *CreateRuntimeVersionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRuntimeVersionRequest.Size(m)
}
func (m *CreateRuntimeVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuntimeVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuntimeVersionRequest proto.InternalMessageInfo

func (m *CreateRuntimeVersionRequest) GetRuntimeVersion() *RuntimeVersion {
	if m != nil {
		return m.RuntimeVersion
	}
	return nil
}

type CreateRuntimeVersionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuntimeVersionResponse) Reset()         { *m = CreateRuntimeVersionResponse{} }
func (m *CreateRuntimeVersionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRuntimeVersionResponse) ProtoMessage()    {}
func (*CreateRuntimeVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{2}
}

func (m *CreateRuntimeVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuntimeVersionResponse.Unmarshal(m, b)
}
func (m *CreateRuntimeVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuntimeVersionResponse.Marshal(b, m, deterministic)
}
func (m *CreateRuntimeVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuntimeVersionResponse.Merge(m, src)
}
func (m *CreateRuntimeVersionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRuntimeVersionResponse.Size(m)
}
func (m *CreateRuntimeVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuntimeVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuntimeVersionResponse proto.InternalMessageInfo

func (m *CreateRuntimeVersionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateRuntimeVersionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CheckRuntimeVersionIsCreatedRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRuntimeVersionIsCreatedRequest) Reset()         { *m = CheckRuntimeVersionIsCreatedRequest{} }
func (m *CheckRuntimeVersionIsCreatedRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRuntimeVersionIsCreatedRequest) ProtoMessage()    {}
func (*CheckRuntimeVersionIsCreatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{3}
}

func (m *CheckRuntimeVersionIsCreatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRuntimeVersionIsCreatedRequest.Unmarshal(m, b)
}
func (m *CheckRuntimeVersionIsCreatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRuntimeVersionIsCreatedRequest.Marshal(b, m, deterministic)
}
func (m *CheckRuntimeVersionIsCreatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRuntimeVersionIsCreatedRequest.Merge(m, src)
}
func (m *CheckRuntimeVersionIsCreatedRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRuntimeVersionIsCreatedRequest.Size(m)
}
func (m *CheckRuntimeVersionIsCreatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRuntimeVersionIsCreatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRuntimeVersionIsCreatedRequest proto.InternalMessageInfo

func (m *CheckRuntimeVersionIsCreatedRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CheckRuntimeVersionIsCreatedRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CheckRuntimeVersionIsCreatedResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRuntimeVersionIsCreatedResponse) Reset()         { *m = CheckRuntimeVersionIsCreatedResponse{} }
func (m *CheckRuntimeVersionIsCreatedResponse) String() string { return proto.CompactTextString(m) }
func (*CheckRuntimeVersionIsCreatedResponse) ProtoMessage()    {}
func (*CheckRuntimeVersionIsCreatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0e5095094a8d27f, []int{4}
}

func (m *CheckRuntimeVersionIsCreatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRuntimeVersionIsCreatedResponse.Unmarshal(m, b)
}
func (m *CheckRuntimeVersionIsCreatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRuntimeVersionIsCreatedResponse.Marshal(b, m, deterministic)
}
func (m *CheckRuntimeVersionIsCreatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRuntimeVersionIsCreatedResponse.Merge(m, src)
}
func (m *CheckRuntimeVersionIsCreatedResponse) XXX_Size() int {
	return xxx_messageInfo_CheckRuntimeVersionIsCreatedResponse.Size(m)
}
func (m *CheckRuntimeVersionIsCreatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRuntimeVersionIsCreatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRuntimeVersionIsCreatedResponse proto.InternalMessageInfo

func (m *CheckRuntimeVersionIsCreatedResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CheckRuntimeVersionIsCreatedResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RuntimeVersion)(nil), "runtime.RuntimeVersion")
	proto.RegisterType((*CreateRuntimeVersionRequest)(nil), "runtime.CreateRuntimeVersionRequest")
	proto.RegisterType((*CreateRuntimeVersionResponse)(nil), "runtime.CreateRuntimeVersionResponse")
	proto.RegisterType((*CheckRuntimeVersionIsCreatedRequest)(nil), "runtime.CheckRuntimeVersionIsCreatedRequest")
	proto.RegisterType((*CheckRuntimeVersionIsCreatedResponse)(nil), "runtime.CheckRuntimeVersionIsCreatedResponse")
}

func init() { proto.RegisterFile("runtimepb/runtime.proto", fileDescriptor_d0e5095094a8d27f) }

var fileDescriptor_d0e5095094a8d27f = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x2a, 0xcd, 0x2b,
	0xc9, 0xcc, 0x4d, 0x2d, 0x48, 0xd2, 0x87, 0xb2, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xd8,
	0xa1, 0x5c, 0x25, 0x13, 0x2e, 0xbe, 0x20, 0x08, 0x33, 0x2c, 0xb5, 0xa8, 0x38, 0x33, 0x3f, 0x4f,
	0x88, 0x8f, 0x8b, 0x29, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88, 0x29, 0x33, 0x45,
	0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09, 0x2c, 0x02, 0x66, 0x2b, 0xc5, 0x71,
	0x49, 0x3b, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0xa2, 0xea, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0xb2, 0xe7, 0xe2, 0x2b, 0x42, 0x91, 0x00, 0x1b, 0xc7, 0x6d, 0x24, 0xae, 0x07, 0x73, 0x05,
	0x9a, 0x3e, 0x34, 0xe5, 0x4a, 0x41, 0x5c, 0x32, 0xd8, 0xcd, 0x2f, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0x15, 0x92, 0xe0, 0x62, 0x2f, 0x2e, 0x4d, 0x4e, 0x4e, 0x2d, 0x2e, 0x06, 0x9b, 0xcc, 0x11, 0x04,
	0xe3, 0x82, 0x64, 0x72, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x61, 0x0e, 0x86, 0x71, 0x95, 0x3c, 0xb9,
	0x94, 0x9d, 0x33, 0x52, 0x93, 0xb3, 0x51, 0x8d, 0xf4, 0x2c, 0x86, 0x58, 0x94, 0x02, 0x73, 0x3b,
	0x31, 0xde, 0x8f, 0xe2, 0x52, 0xc1, 0x6f, 0x14, 0xf9, 0xce, 0x34, 0xfa, 0xcb, 0xc8, 0x25, 0x8a,
	0x6a, 0x6e, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x50, 0x2a, 0x97, 0x08, 0xb6, 0x40, 0x11,
	0x52, 0x81, 0x87, 0x2a, 0x9e, 0x38, 0x91, 0x52, 0x25, 0xa0, 0x0a, 0xe2, 0x64, 0x25, 0x06, 0xa1,
	0x5a, 0x2e, 0x19, 0x7c, 0x9e, 0x13, 0xd2, 0x41, 0x18, 0x44, 0x38, 0x38, 0xa5, 0x74, 0x89, 0x54,
	0x0d, 0xb3, 0xde, 0x89, 0x3b, 0x8a, 0x13, 0x9e, 0x68, 0x93, 0xd8, 0xc0, 0xa9, 0xd5, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x4d, 0xa0, 0xf3, 0x51, 0xc8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RuntimeVersionServiceClient is the client API for RuntimeVersionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuntimeVersionServiceClient interface {
	CreateRuntimeVersion(ctx context.Context, in *CreateRuntimeVersionRequest, opts ...grpc.CallOption) (*CreateRuntimeVersionResponse, error)
	CheckRuntimeVersionIsCreated(ctx context.Context, in *CheckRuntimeVersionIsCreatedRequest, opts ...grpc.CallOption) (*CheckRuntimeVersionIsCreatedResponse, error)
}

type runtimeVersionServiceClient struct {
	cc *grpc.ClientConn
}

func NewRuntimeVersionServiceClient(cc *grpc.ClientConn) RuntimeVersionServiceClient {
	return &runtimeVersionServiceClient{cc}
}

func (c *runtimeVersionServiceClient) CreateRuntimeVersion(ctx context.Context, in *CreateRuntimeVersionRequest, opts ...grpc.CallOption) (*CreateRuntimeVersionResponse, error) {
	out := new(CreateRuntimeVersionResponse)
	err := c.cc.Invoke(ctx, "/runtime.RuntimeVersionService/CreateRuntimeVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeVersionServiceClient) CheckRuntimeVersionIsCreated(ctx context.Context, in *CheckRuntimeVersionIsCreatedRequest, opts ...grpc.CallOption) (*CheckRuntimeVersionIsCreatedResponse, error) {
	out := new(CheckRuntimeVersionIsCreatedResponse)
	err := c.cc.Invoke(ctx, "/runtime.RuntimeVersionService/CheckRuntimeVersionIsCreated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeVersionServiceServer is the server API for RuntimeVersionService service.
type RuntimeVersionServiceServer interface {
	CreateRuntimeVersion(context.Context, *CreateRuntimeVersionRequest) (*CreateRuntimeVersionResponse, error)
	CheckRuntimeVersionIsCreated(context.Context, *CheckRuntimeVersionIsCreatedRequest) (*CheckRuntimeVersionIsCreatedResponse, error)
}

// UnimplementedRuntimeVersionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRuntimeVersionServiceServer struct {
}

func (*UnimplementedRuntimeVersionServiceServer) CreateRuntimeVersion(ctx context.Context, req *CreateRuntimeVersionRequest) (*CreateRuntimeVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRuntimeVersion not implemented")
}
func (*UnimplementedRuntimeVersionServiceServer) CheckRuntimeVersionIsCreated(ctx context.Context, req *CheckRuntimeVersionIsCreatedRequest) (*CheckRuntimeVersionIsCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRuntimeVersionIsCreated not implemented")
}

func RegisterRuntimeVersionServiceServer(s *grpc.Server, srv RuntimeVersionServiceServer) {
	s.RegisterService(&_RuntimeVersionService_serviceDesc, srv)
}

func _RuntimeVersionService_CreateRuntimeVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuntimeVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeVersionServiceServer).CreateRuntimeVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runtime.RuntimeVersionService/CreateRuntimeVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeVersionServiceServer).CreateRuntimeVersion(ctx, req.(*CreateRuntimeVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeVersionService_CheckRuntimeVersionIsCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRuntimeVersionIsCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeVersionServiceServer).CheckRuntimeVersionIsCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runtime.RuntimeVersionService/CheckRuntimeVersionIsCreated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeVersionServiceServer).CheckRuntimeVersionIsCreated(ctx, req.(*CheckRuntimeVersionIsCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RuntimeVersionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.RuntimeVersionService",
	HandlerType: (*RuntimeVersionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRuntimeVersion",
			Handler:    _RuntimeVersionService_CreateRuntimeVersion_Handler,
		},
		{
			MethodName: "CheckRuntimeVersionIsCreated",
			Handler:    _RuntimeVersionService_CheckRuntimeVersionIsCreated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtimepb/runtime.proto",
}
