// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
	"github.com/konstellation-io/kre/engine/admin-api/domain/entity"
)

type ConfigurationVariablesInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type CreateUserInput struct {
	Email       string             `json:"email"`
	AccessLevel entity.AccessLevel `json:"accessLevel"`
}

type CreateVersionInput struct {
	File graphql.Upload `json:"file"`
}

type DeleteAPITokenInput struct {
	ID string `json:"id"`
}

type GenerateAPITokenInput struct {
	Name string `json:"name"`
}

type LogPage struct {
	Cursor *string           `json:"cursor"`
	Items  []*entity.NodeLog `json:"items"`
}

type PublishVersionInput struct {
	VersionID string `json:"versionId"`
	Comment   string `json:"comment"`
}

type SettingsInput struct {
	AuthAllowedDomains    []string `json:"authAllowedDomains"`
	SessionLifetimeInDays *int     `json:"sessionLifetimeInDays"`
}

type StartVersionInput struct {
	VersionID string `json:"versionId"`
	Comment   string `json:"comment"`
}

type StopVersionInput struct {
	VersionID string `json:"versionId"`
	Comment   string `json:"comment"`
}

type UnpublishVersionInput struct {
	VersionID string `json:"versionId"`
	Comment   string `json:"comment"`
}

type UpdateAccessLevelInput struct {
	UserIds     []string           `json:"userIds"`
	AccessLevel entity.AccessLevel `json:"accessLevel"`
	Comment     string             `json:"comment"`
}

type UpdateConfigurationInput struct {
	VersionID              string                         `json:"versionId"`
	ConfigurationVariables []*ConfigurationVariablesInput `json:"configurationVariables"`
}

type UsersInput struct {
	UserIds []string `json:"userIds"`
	Comment string   `json:"comment"`
}

type RuntimeStatus string

const (
	RuntimeStatusCreating RuntimeStatus = "CREATING"
	RuntimeStatusStarted  RuntimeStatus = "STARTED"
	RuntimeStatusError    RuntimeStatus = "ERROR"
)

var AllRuntimeStatus = []RuntimeStatus{
	RuntimeStatusCreating,
	RuntimeStatusStarted,
	RuntimeStatusError,
}

func (e RuntimeStatus) IsValid() bool {
	switch e {
	case RuntimeStatusCreating, RuntimeStatusStarted, RuntimeStatusError:
		return true
	}
	return false
}

func (e RuntimeStatus) String() string {
	return string(e)
}

func (e *RuntimeStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RuntimeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RuntimeStatus", str)
	}
	return nil
}

func (e RuntimeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
