# Generated by KRE tools. DO NOT EDIT!

# JUST A PLACEHOLDER FOR EACH VERSION AUTO GENERATED ENTRYPOINT


class Entrypoint:
    def __init__(self, logger, nc, subjects):
        raise Exception(f"error creating Entrypoint.")
