// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/resourcemetricspb/resourcemetrics.proto

package resourcemetricspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Date                 string   `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	CPU                  float32  `protobuf:"fixed32,2,opt,name=CPU,proto3" json:"CPU,omitempty"`
	Mem                  float32  `protobuf:"fixed32,3,opt,name=Mem,proto3" json:"Mem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_51f2826e78bd2e23, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Response) GetCPU() float32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

func (m *Response) GetMem() float32 {
	if m != nil {
		return m.Mem
	}
	return 0
}

type VersionRequest struct {
	VersionName          string   `protobuf:"bytes,1,opt,name=VersionName,proto3" json:"VersionName,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	FromDate             string   `protobuf:"bytes,3,opt,name=FromDate,proto3" json:"FromDate,omitempty"`
	ToDate               string   `protobuf:"bytes,4,opt,name=ToDate,proto3" json:"ToDate,omitempty"`
	Step                 int32    `protobuf:"varint,5,opt,name=Step,proto3" json:"Step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51f2826e78bd2e23, []int{1}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

func (m *VersionRequest) GetVersionName() string {
	if m != nil {
		return m.VersionName
	}
	return ""
}

func (m *VersionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *VersionRequest) GetFromDate() string {
	if m != nil {
		return m.FromDate
	}
	return ""
}

func (m *VersionRequest) GetToDate() string {
	if m != nil {
		return m.ToDate
	}
	return ""
}

func (m *VersionRequest) GetStep() int32 {
	if m != nil {
		return m.Step
	}
	return 0
}

type WatchVersionRequest struct {
	VersionName          string   `protobuf:"bytes,1,opt,name=VersionName,proto3" json:"VersionName,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	FromDate             string   `protobuf:"bytes,3,opt,name=FromDate,proto3" json:"FromDate,omitempty"`
	Step                 int32    `protobuf:"varint,4,opt,name=Step,proto3" json:"Step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchVersionRequest) Reset()         { *m = WatchVersionRequest{} }
func (m *WatchVersionRequest) String() string { return proto.CompactTextString(m) }
func (*WatchVersionRequest) ProtoMessage()    {}
func (*WatchVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51f2826e78bd2e23, []int{2}
}

func (m *WatchVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchVersionRequest.Unmarshal(m, b)
}
func (m *WatchVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchVersionRequest.Marshal(b, m, deterministic)
}
func (m *WatchVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchVersionRequest.Merge(m, src)
}
func (m *WatchVersionRequest) XXX_Size() int {
	return xxx_messageInfo_WatchVersionRequest.Size(m)
}
func (m *WatchVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchVersionRequest proto.InternalMessageInfo

func (m *WatchVersionRequest) GetVersionName() string {
	if m != nil {
		return m.VersionName
	}
	return ""
}

func (m *WatchVersionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *WatchVersionRequest) GetFromDate() string {
	if m != nil {
		return m.FromDate
	}
	return ""
}

func (m *WatchVersionRequest) GetStep() int32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func init() {
	proto.RegisterType((*Response)(nil), "resourcemetrics.Response")
	proto.RegisterType((*VersionRequest)(nil), "resourcemetrics.VersionRequest")
	proto.RegisterType((*WatchVersionRequest)(nil), "resourcemetrics.WatchVersionRequest")
}

func init() {
	proto.RegisterFile("proto/resourcemetricspb/resourcemetrics.proto", fileDescriptor_51f2826e78bd2e23)
}

var fileDescriptor_51f2826e78bd2e23 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0xdd, 0x36, 0x2d, 0xcd, 0x28, 0x7e, 0x4c, 0xa1, 0xc4, 0x22, 0x18, 0x82, 0x87, 0x5c,
	0xac, 0xa2, 0x6f, 0x50, 0x45, 0x41, 0x88, 0xc8, 0xc6, 0x0f, 0xf0, 0x96, 0x86, 0x01, 0x73, 0xd8,
	0xee, 0xba, 0xbb, 0xf5, 0x0d, 0x7c, 0x07, 0x5f, 0xc5, 0xb7, 0x93, 0x6c, 0x13, 0x5b, 0x13, 0xf1,
	0xe8, 0x29, 0x33, 0xbf, 0x19, 0x26, 0xff, 0xfd, 0xcf, 0xc0, 0xb1, 0xd2, 0xd2, 0xca, 0x13, 0x4d,
	0x46, 0x2e, 0x74, 0x4e, 0x82, 0xac, 0x2e, 0x72, 0xa3, 0x66, 0x4d, 0x32, 0x71, 0x7d, 0xb8, 0xd3,
	0xc0, 0xd1, 0x14, 0x06, 0x9c, 0x8c, 0x92, 0x73, 0x43, 0x88, 0xe0, 0x5d, 0x66, 0x96, 0x02, 0x16,
	0xb2, 0xd8, 0xe7, 0x2e, 0xc6, 0x5d, 0xe8, 0x5e, 0xdc, 0x3d, 0x04, 0x9d, 0x90, 0xc5, 0x1d, 0x5e,
	0x86, 0x25, 0x49, 0x48, 0x04, 0xdd, 0x25, 0x49, 0x48, 0x44, 0x1f, 0x0c, 0xb6, 0x1f, 0x49, 0x9b,
	0x42, 0xce, 0x39, 0xbd, 0x2e, 0xc8, 0x58, 0x0c, 0x61, 0xb3, 0x22, 0xb7, 0x99, 0xa8, 0x27, 0xae,
	0x23, 0x3c, 0x00, 0xbf, 0xfc, 0x1a, 0x95, 0xe5, 0xe4, 0xc6, 0xfb, 0x7c, 0x05, 0x70, 0x0c, 0x83,
	0x2b, 0x2d, 0x85, 0x93, 0xd3, 0x75, 0xc5, 0xef, 0x1c, 0x47, 0xd0, 0xbf, 0x97, 0xae, 0xe2, 0xb9,
	0x4a, 0x95, 0x95, 0xf2, 0x53, 0x4b, 0x2a, 0xe8, 0x85, 0x2c, 0xee, 0x71, 0x17, 0x47, 0xef, 0x0c,
	0x86, 0x4f, 0x99, 0xcd, 0x5f, 0xfe, 0x51, 0x5f, 0xad, 0xc3, 0x5b, 0xe9, 0x38, 0xfb, 0x64, 0x30,
	0xe2, 0x95, 0xf5, 0xc9, 0xd2, 0xfa, 0x94, 0xf4, 0x5b, 0x91, 0x13, 0xde, 0x00, 0x5c, 0x93, 0xad,
	0x7e, 0x8d, 0x87, 0x93, 0xe6, 0xe2, 0x7e, 0x2a, 0x1f, 0xef, 0xb7, 0x1a, 0xea, 0xfd, 0x45, 0x1b,
	0x98, 0xc2, 0xd6, 0xfa, 0x6b, 0xf1, 0xa8, 0xd5, 0xfc, 0x8b, 0x19, 0x7f, 0x8e, 0x3c, 0x65, 0xd3,
	0xe1, 0xf3, 0x5e, 0xeb, 0xbc, 0x66, 0x7d, 0x77, 0x4f, 0xe7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xca, 0x9b, 0xa3, 0x87, 0x80, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourceMetricsServiceClient is the client API for ResourceMetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceMetricsServiceClient interface {
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Response, error)
	WatchVersion(ctx context.Context, in *WatchVersionRequest, opts ...grpc.CallOption) (ResourceMetricsService_WatchVersionClient, error)
}

type resourceMetricsServiceClient struct {
	cc *grpc.ClientConn
}

func NewResourceMetricsServiceClient(cc *grpc.ClientConn) ResourceMetricsServiceClient {
	return &resourceMetricsServiceClient{cc}
}

func (c *resourceMetricsServiceClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/resourcemetrics.ResourceMetricsService/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceMetricsServiceClient) WatchVersion(ctx context.Context, in *WatchVersionRequest, opts ...grpc.CallOption) (ResourceMetricsService_WatchVersionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ResourceMetricsService_serviceDesc.Streams[0], "/resourcemetrics.ResourceMetricsService/WatchVersion", opts...)
	if err != nil {
		return nil, err
	}
	x := &resourceMetricsServiceWatchVersionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResourceMetricsService_WatchVersionClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type resourceMetricsServiceWatchVersionClient struct {
	grpc.ClientStream
}

func (x *resourceMetricsServiceWatchVersionClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResourceMetricsServiceServer is the server API for ResourceMetricsService service.
type ResourceMetricsServiceServer interface {
	GetVersion(context.Context, *VersionRequest) (*Response, error)
	WatchVersion(*WatchVersionRequest, ResourceMetricsService_WatchVersionServer) error
}

// UnimplementedResourceMetricsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedResourceMetricsServiceServer struct {
}

func (*UnimplementedResourceMetricsServiceServer) GetVersion(ctx context.Context, req *VersionRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (*UnimplementedResourceMetricsServiceServer) WatchVersion(req *WatchVersionRequest, srv ResourceMetricsService_WatchVersionServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchVersion not implemented")
}

func RegisterResourceMetricsServiceServer(s *grpc.Server, srv ResourceMetricsServiceServer) {
	s.RegisterService(&_ResourceMetricsService_serviceDesc, srv)
}

func _ResourceMetricsService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceMetricsServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resourcemetrics.ResourceMetricsService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceMetricsServiceServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceMetricsService_WatchVersion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchVersionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceMetricsServiceServer).WatchVersion(m, &resourceMetricsServiceWatchVersionServer{stream})
}

type ResourceMetricsService_WatchVersionServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type resourceMetricsServiceWatchVersionServer struct {
	grpc.ServerStream
}

func (x *resourceMetricsServiceWatchVersionServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _ResourceMetricsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resourcemetrics.ResourceMetricsService",
	HandlerType: (*ResourceMetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _ResourceMetricsService_GetVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchVersion",
			Handler:       _ResourceMetricsService_WatchVersion_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/resourcemetricspb/resourcemetrics.proto",
}
