{{- $protocol := ternary  "https" "http" .Values.adminUI.tls.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-admin-ui-configmap
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-ui
data:
  config.json: |
    {
      "API_BASE_URL": "{{ $protocol }}://{{ .Values.config.admin.apiHost }}",
      "MONORUNTIME_MODE": "1"
    }
