apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  labels:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-ui
spec:
  clusterIP: None
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
  selector:
    {{- include "kre.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-ui
