apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "runtime.labels" . | nindent 6 }}
      app: mongo-writer
  template:
    metadata:
      labels:
        {{- include "runtime.labels" . | nindent 8 }}
        app: mongo-writer
    spec:
      containers:
        - name: {{ .Release.Name }}-mongo-writer
          image: {{ .Values.mongoWriter.image.repository }}:{{ .Values.mongoWriter.image.tag }}
          imagePullPolicy: {{ .Values.mongoWriter.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secrets
          env:
          - name: KRE_RUNTIME_MONGO_URI
            {{- if .Values.config.mongodb.connectionString.secretName }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.config.mongodb.connectionString.secretName }}
                key: {{ .Values.config.mongodb.connectionString.secretKey }}
            {{- else }}
            value: {{ .Values.config.mongodb.connectionString.uri }}
            {{- end }}
