apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "runtime.fullname" . }}-chronograf
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: chronograf.{{ .Values.runtime.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: chronograf
              servicePort: 80
