apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chronograf-pvc
  labels:
    app: chronograf
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
