apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongoexpress
  labels:
    {{- include "mongoExpress.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mongoExpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mongoExpress.labels" . | nindent 8 }}
    spec:
      containers:
        - name: kre-mongo-express
          image: mongo-express:0.54.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: kre-mongo-express-secret
            - configMapRef:
                name: {{ .Release.Name }}-mongo
          ports:
            - containerPort: 8081
