apiVersion: apps/v1
kind: Deployment
metadata:
  name: kre-mongo-express
  labels:
    {{- include "mongoExpress.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mongoExpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mongoExpress.labels" . | nindent 8 }}
    spec:
      containers:
        - name: kre-mongo-express
          image: mongo-express:0.54.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "kre-mongo-0"
            - name: ME_CONFIG_OPTIONS_READONLY
              value: "true"
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "false"
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: "data"
            - name: ME_CONFIG_SITE_BASEURL
              value: /database/{{ .Release.Namespace }}
          envFrom:
            - secretRef:
                name: kre-mongo-express-secret
          ports:
            - containerPort: 8081
