apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongo.name" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: "{{ include "mongo.name" . }}"
  selector:
    matchLabels:
      {{- include "mongodb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mongodb.labels" . | nindent 8 }}
    spec:
      containers:
        - name: mongo
          image: mongo:4.2.8
          imagePullPolicy: IfNotPresent
          args:
            - "--replSet=rs0"
          envFrom:
            - secretRef:
                name: {{ include "mongo.name" . }}
            - secretRef:
                name: {{ include "mongoExpress.name" . }}
          env:
            - name: MONGO_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mongo.name" . }}
                  key: ME_CONFIG_MONGODB_AUTH_DATABASE
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: {{ include "mongo.name" . }}-pvc
              mountPath: "/data/db"
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: init-scripts
          configMap:
            name: {{ include "mongo.name" . }}-init
            defaultMode: 0777
    {{- with .Values.mongodb.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.mongodb.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.mongodb.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "mongo.name" . }}-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.mongodb.persistentVolume.storageClass }}
        resources:
          requests:
            storage:  {{ .Values.mongodb.persistentVolume.size }}
