---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nats-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
data:
  nats.conf: |
    # NATS Clients Port
    port: {{ .Values.nats.client.port }}

    ###############
    #             #
    # Monitoring  #
    #             #
    ###############
    http: 8222
    server_name: $POD_NAME

    ###################################
    #                                 #
    # NATS JetStream                  #
    #                                 #
    ###################################
    jetstream {
      {{- if .Values.nats.jetstream.storage.enabled }}
      store_dir: {{ .Values.nats.jetstream.storage.storageDirectory }}
      {{- end }}

      {{- if .Values.nats.jetstream.memStorage.enabled }}
      max_mem: {{ .Values.nats.jetstream.memStorage.size }}
      {{- end }}

      max_file_store: {{ .Values.nats.jetstream.storage.size }}
    }

    ###################################
    #                                 #
    # Logging config                  #
    #                                 #
    ###################################
    {{- with .Values.nats.logging.debug }}
    debug: {{ . }}
    {{- end }}
    {{- with .Values.nats.logging.trace }}
    trace:  {{ . }}
    {{- end }}
    {{- with .Values.nats.logging.logtime }}
    logtime: {{ . }}
    {{- end }}

    {{- with .Values.nats.limits.maxConnections }}
    max_connections: {{ . }}
    {{- end }}

    {{- with .Values.nats.limits.maxSubscriptions }}
    max_subscriptions: {{ . }}
    {{- end }}

    {{- with .Values.nats.limits.maxPending }}
    max_pending: {{ . }}
    {{- end }}

    {{- with .Values.nats.limits.maxControlLine }}
    max_control_line: {{ . }}
    {{- end }}

    {{- with .Values.nats.limits.maxPayload }}
    max_payload: {{ . }}
    {{- end }}

    {{- with .Values.nats.limits.pingInterval }}
    ping_interval: {{ . }}
    {{- end }}

    {{- with .Values.nats.limits.maxPings }}
    ping_max: {{ . }}
    {{- end }}

    {{- with .Values.nats.limits.writeDeadline }}
    write_deadline: {{ . }}
    {{- end }}

    {{- with .Values.nats.limits.lameDuckGracePeriod }}
    lame_duck_grace_period: {{ . }}
    {{- end }}

    {{- with .Values.nats.limits.lameDuckDuration }}
    lame_duck_duration: {{ . }}
    {{- end }}
