apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: kre
type: Opaque
data:
  KRE_MONGODB_ADDRESS: {{ printf "mongodb://%s:%s@kre-mongo:27017/%s" .Values.mongodb.mongodbUsername .Values.mongodb.mongodbPassword "admin"| b64enc }}
  KRE_AUTH_JWT_SIGN_SECRET: {{ .Values.config.auth.jwtSignSecret | b64enc }}
  {{- if .Values.config.smtp.enabled}}
  KRE_SMTP_USER: {{ .Values.config.smtp.user | b64enc }}
  KRE_SMTP_PASS: {{ .Values.config.smtp.pass | b64enc }}
  {{- end }}
  ## ApiToken
  KRE_AUTH_API_TOKEN_CIPHER_SECRET: "{{ .Values.config.auth.apiToken.cipherSecret | b64enc }}"

