apiVersion: v1
kind: Secret
metadata:
  name: kre-minio-secret
  labels:
    {{ include "runtime.labels" . | nindent 4 }}
    app: kre-minio-secret
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.minio.credentials.accessKey | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.minio.credentials.secretKey | b64enc }}
