apiVersion: v1
kind: Service
metadata:
  name: kre-minio
  labels:
    {{ include "runtime.labels" . | nindent 4 }}
    app: kre-minio
spec:
  clusterIP: None
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: kre-minio
