{{ if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
  {{ else if .Capabilities.APIVersions.Has "apps/v1beta1" }}
apiVersion: apps/v1beta1
  {{ end }}
kind: StatefulSet
metadata:
  name: kre-minio
  labels:
    {{ include "runtime.labels" . | nindent 4 }}
    app: kre-minio
spec:
  replicas: 1
  serviceName: kre-minio
  selector:
    matchLabels:
      {{- include "runtime.labels" . | nindent 6 }}
      app: kre-minio
  template:
    metadata:
      labels:
        {{ include "runtime.labels" . | nindent 8 }}
        app: kre-minio
    spec:
      containers:
        - name: minio
          image: tetrash/minio-multiarch:latest
          args:
            - server
            - /data
          envFrom:
            - secretRef:
                name: kre-minio-secret
          volumeMounts:
            - name: {{ .Release.Namespace }}-kre-minio-pvc
              mountPath: "/data"
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Namespace }}-kre-minio-pvc
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: {{ .Values.sharedStorageClass }}
        resources:
          requests:
            storage: {{ .Values.minio.storage.size }}
