helmDefaults:
  createNamespace: true
  atomic: false
  verify: false
  wait: true
  timeout: 3600
  disableValidation: true

templates:
  default: &default
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    namespace: kre
    values:
    - "values/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl"
    - "values/{{`{{ .Release.Name }}`}}/values.yaml"

repositories:
  - name: mongodb
    url: https://mongodb.github.io/helm-charts
  - name: bedag
    url: https://bedag.github.io/helm-charts/

releases:
  - name: "mongodb-operator"
    <<: *default
    chart: mongodb/community-operator

  - name: "mongodb-database"
    <<: *default
    chart: bedag/raw
    needs:
    - kre/mongodb-operator

  - name: prometheus
    <<: *default
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 39.13.3

  - name: monitoring-resources
    <<: *default
    chart: "bedag/raw"
    namespace: monitoring
    needs:
      - prometheus

  - name: "{{ env "RELEASE_NAME" | default "kre-local" }}"
    <<: *default
    chart: ../../helm/kre
    needs:
    - kre/mongodb-database
