export const COLORS = {
  BLUE: '#00A5CC',
  GRAY_DISABLED: '#1D1E23'
};

export const ENDPOINT = {
  SUBMIT_MAGIC_LINK: 'signin',
  VALIDATE_MAGIC_LINK: 'signin/verify'
};

export const STATES = {
  INITIALIZING: 'INITIALIZING',
  LOADING: 'LOADING',
  DISABLED: 'DISABLED',
  ERROR: 'ERROR',
  ALERT: 'ALERT',
  SUCCESS: 'SUCCESS',
  DEFAULT: 'DEFAULT',
  HOVER: 'HOVER',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};
