// Code generated by MockGen. DO NOT EDIT.
// Source: validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	krt "github.com/konstellation-io/kre/engine/admin-api/domain/usecase/krt"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// CheckExecutables mocks base method.
func (m *MockValidator) CheckExecutables(krt *krt.Krt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExecutables", krt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckExecutables indicates an expected call of CheckExecutables.
func (mr *MockValidatorMockRecorder) CheckExecutables(krt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExecutables", reflect.TypeOf((*MockValidator)(nil).CheckExecutables), krt)
}

// Run mocks base method.
func (m *MockValidator) Run(krt *krt.Krt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", krt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockValidatorMockRecorder) Run(krt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockValidator)(nil).Run), krt)
}
